### PR TITLE
jsonld import export

### PR DESCRIPTION
**Pull request by aarongundel**
IMPORTANT:  Do not merge until #7905 is merged.

### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

i8ln business data import/export

### Issues Solved

#7940 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by apeters — CHANGES_REQUESTED** [review]
I added a test that currently fails, but I think should pass.

**Comment by aarongundel** [comment]
@apeters I've addressed the test that was failing; I modified the is_multilingual_string_node function to stop checking for cardinality; as that does not seem necessary and probably a holdover from earlier code.  Also, I was getting failures from api_tests.py - some of the resources therein contained improperly formatted (for 7.x/i18n) strings.  I corrected those to get this passing

**Review by apeters — CHANGES_REQUESTED** [review]
I think this PR should be based off of the i18n_ui_and_data branch.  It's hard to know which files to actually review here.

**Review by apeters — APPROVED** [review]
works as expected

**Pull request merged**
