### PR TITLE
preserving cardinality on copy/append graph

### PR DESCRIPTION
**Pull request by robgaston**
re: #1011

### CODE REVIEW

**Comment by dwuthrich** [comment]
Neitehr cardinality nor card labels are preserved when appending a branch to a resource.  Use the following brach to test:

**Comment by dwuthrich** [comment]
[Places export.json.zip](https://github.com/archesproject/arches/files/562584/Places.export.json.zip)

**Comment by robgaston** [comment]
@dwuthrich let's move this thread over to #862 as it is not really related to this issue

**Comment by dwuthrich** [comment]
@robgaston Ok

**Pull request merged**
