### PR TITLE
make sure concept ids are uuids

### PR DESCRIPTION
**Pull request by apeters**
re #7822

### CODE REVIEW

**Comment by apeters** [comment]
To test:
- Unzip the attached file
- Import the model `Textual Work.json`
- Load the json-ld file with this command
- `python manage.py load_jsonld -s data_test_textual_work/ -ow overwrite`

It should fail to load w/o the fix.  

[Test data and model.zip](https://github.com/archesproject/arches/files/7180810/Test.data.and.model.zip)

**Comment by aarongundel** [comment]
Tested but (per slack) unable to validate the fix.  Stack trace follows.  Validated that LinkedArt is loaded.  

`Found possible models: ['textual_work']
Loading textual_work
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/web_root/arches/arches/management/commands/load_jsonld.py", line 128, in handle
    self.load_resources(options)
  File "/web_root/arches/arches/management/commands/load_jsonld.py", line 172, in load_resources
    self.reader.graphtree = self.reader.process_graph(graphid)
  File "/web_root/arches/arches/app/utils/data_management/resources/formats/rdffile.py", line 315, in process_graph
    node["extra_class"].append(self.root_ontologyclass_lookup[gid])
KeyError: '1810d182-b4b5-11ea-84f7-3af9d3b32b71'`

**Comment by aarongundel** [comment]
Alexei demo'd the fix for me - difficult to test because we need a graph that has the issue - looks like an effective fix for this issue.

**Review by aarongundel — APPROVED** [review]

**Comment by probonas** [comment]
We are experiencing the same issue as described above. We are using the version 6.0.0 of arches, but we are unable to load these exact data. Could someone provide some insight regarding this?

**Pull request merged**
