### PR TITLE
10780 guess node mappings

### PR DESCRIPTION
**Pull request by whatisgalen**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

https://github.com/archesproject/arches/assets/8366985/9f0191ca-a306-4408-a20d-99b3292b4892

### Issues Solved

#10780 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: @scholiumtech
*   Found by: @whatisgalen 
*   Tested by: @ 
*   Designed by: @whatisgalen

### CODE REVIEW

**Review by njkim — COMMENTED** [review]
@whatisgalen It looks like a nice addition to the importer and it works great.
But it is little bit concerning that this is deprecated quite a while ago.
Do you think if there are any alternatives or other way to implement this?

**Review by njkim — COMMENTED** [review]
@whatisgalen
Maybe my local arches is not properly set up for this but I am getting an error saying.
> TypeError: FuzzySet is not a function l.66

Some other minor suggestions are:
1. Can we consider something more authoritative than "Guess Mappable Nodes" (which is a little vague too)? Something like "Match Columns to Nodes" (nodes to columns? :) )?

2. Can we move the button to the right side of `the column names in the first row` so that the table can show more contents?

3. When the column names are not in the csv, the table automatically assigns the integer numbers to the column. This does not break the ui but there is an error when trying to convert to column name to the lowercase. One option is to hide button (or disable) when there are not column names in the csv, ie. `the column names in the first row` is off.

4. I am not sure if we need to add "fuzzyset" to javascipt.htm?

**Comment by chiatt** [comment]
> @whatisgalen Maybe my local arches is not properly set up for this but I am getting an error saying.
> 
> > TypeError: FuzzySet is not a function l.66
> 
> Some other minor suggestions are:
> 
> 1. Can we consider something more authoritative than "Guess Mappable Nodes" (which is a little vague too)? Something like "Match Columns to Nodes" (nodes to columns? :) )?
> 2. Can we move the button to the right side of `the column names in the first row` so that the table can show more contents?
> 3. When the column names are not in the csv, the table automatically assigns the integer numbers to the column. This does not break the ui but there is an error when trying to convert to column name to the lowercase. One option is to hide button (or disable) when there are not column names in the csv, ie. `the column names in the first row` is off.
> 4. I am not sure if we need to add "fuzzyset" to javascipt.htm?

I agree with @njkim, 'Match Columns to Nodes' (or nodes to columns) is more explicit and although 'map' makes sense for more technical folks, 'match' would probably be clearer for most users.

**Comment by whatisgalen** [comment]
@njkim @chiatt all requested changes pushed in latest

**Review by njkim — APPROVED** [review]
It works great.

**Pull request merged**
