### PR TITLE
Check bnodeid exists in tile data

### PR DESCRIPTION
**Pull request by probonas**
### Types of changes

-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Checking that the _bnodeid_ exists in the tile's data before accessing it, allowed the loader to not fail with a _KeyError_ exception but rather raise an exception with an appropriate message that revealed the underlying cause of the error, as seen in the screenshot below.

arches-correct-message

Now fixing the cardinality in the model, allowed me to load the desired file.

arches-successful-load

### Issues Solved

#8966 
#

### Checklist

-   [X] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Getty Conservation Institute
*   Found by: @probonas
*   Tested by: @probonas
*   Designed by: @probonas

### CODE REVIEW

**Comment by chiatt** [comment]
Thanks @probonas for this PR. It looks like you want to merge this into master, but it's possible you are working off of dev/6.2.x or dev/6.1.x. Do you know which version you branched off of?

**Comment by probonas** [comment]
Hi @chiatt . I branched off of master, since dev/6.1.x had already been merged to master.

**Comment by chiatt** [comment]
Thanks @probonas, could you point the PR to the dev/6.1.x branch?

**Comment by probonas** [comment]
@chiatt branch off of dev/6.1.x and pointed this PR to the same branch.

**Comment by chiatt** [comment]
Hi @probonas, master was actually based of dev/6.2.x rather than dev/6.1.x. Unfortunately when you branched off of it, it was missing a fix in dev/6.2.x for the migration dependency order. This is the reason why the CI build is failing. I've updated master with that fix. Could you merge either dev/6.2.x or master into your branch? I think that will get the build to pass.

**Comment by chiatt** [comment]
Thanks @probonas, that did the trick.

**Comment by probonas** [comment]
Just let me know if anything else is needed. Thanks a lot for the help

**Comment by apeters** [comment]
Hi @probonas ,
It looks like the only edit you made was with this commit
https://github.com/archesproject/arches/pull/8967/commits/a38440d4810d4aae3b4bad232e1baeed34bcf986
For some reason, there's several other edits that reference code already in dev/6.2.x, maybe because of all the rebasing.
In any case I'd like you to create a brand new branch off of dev/6.2.x and apply your single edit that I referred to above.
Then please submit a new PR with that single edit.
Thanks!

**Comment by apeters** [comment]
this is superseded by #9057

**Pull request closed without merging**
