### PR TITLE
7955 geojson load prop bug

### PR DESCRIPTION
**Pull request by aj-he**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Fixes issue with imported geojson features missing the `nodeId` property 

### Issues Solved

#7955

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @aj-he 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Comment by aj-he** [comment]
@robgaston can you take a look as blocking koop testing for aher

**Comment by robgaston** [comment]
@aj-he I think that we should rework this so that rather than adding the node ids on load, we simply fix the GeoJSON API so that they are not required, as we are simply trying to remove them from the payload in the lines that you specified in the issue (see my comment here: https://github.com/archesproject/arches/issues/7955#issuecomment-962033320)

ultimately, we don't want to require these node ids to be included as properties because they can always be regenerated in code.  The goal is that features loaded must only be valid GeoJSON features, with no special arches requirements.

I think that we can simply change that conditional in api.py into a try/except to get the endpoint working.

**Comment by aj-he** [comment]
@robgaston That's easy enough. My original solution was to check for the `nodeId` key rather than test the value in the GeoJSON api.

Because the property is there in data I have digitised, the assumption is that it is required. Therefore, I adjusted my solution accordingly.

If it is not needed then it should be removed when saving for the same reason you gave?

**Comment by robgaston** [comment]
@aj-he removing those on save would probably be tidier and more proper.  they are used though (and generated when not available) in the web front end, so it would probably be best for that interface to also be responsible for cleaning up it's mess (rather than building that into tile save).  I'd say, let's open a separate ticket to clean that up, as they are innocuous (ie not causing an error or related to the error in #7955) but messy and worse potentially confusing.  I've created this ticket here: #7957

**Comment by aj-he** [comment]
@robgaston great, sounds like a plan

**Comment by aj-he** [comment]
@robgaston Ok, this should be in order now. Could you review?

Could you also look at the koop service PR https://github.com/archesproject/arches-koop/pull/13, which we have been testing alongside this today. Seems to work ok on our small Aircraft dataset.

We can then get going with some ESRI add-in testing of the bigger datasets on Monday/Tuesday.

**Review by robgaston — APPROVED** [review]
looks good - thanks!

**Pull request merged**
