### PR TITLE
new install script for ubuntu to combine trusty_setup and install_arches

### PR DESCRIPTION
**Pull request by mradamcox**
Currently this pulls a settings_local.py file from my own website, which sets MODE = 'DEV' and RESOURCE_GRAPH_LOCATIONS to ...../arches/tests/fixtures/resource_graphs/archesv4_resource.json.

Starting with a blank Ubuntu 14.04 server (I used AWS), this script will install all dependencies and install arches, after which you can run the django dev server.

### CODE REVIEW

**Comment by apeters** [comment]
Instead of pulling the settings_local.py file from a remote location, I'd rather see the file just created dynamically and saved on the file system (assuming that it didn't already exist)

**Comment by apeters** [comment]
@mradamcox , any progress on using a local (non-remote) settings_local.py file?

**Comment by mradamcox** [comment]
Hi Alexei, just seeing this. I worked on this script quite a while ago, and it may need to be updated. Need to at least run bower install, and remove reference to the settings_local.py file I was hosting.

**Comment by mradamcox** [comment]
I'm going to close this pull request because 1. I made it from my master branch, and 2. it's pretty out of date, and 3. more time should be spent on all of this install stuff later anyway.

**Pull request closed without merging**
