### PR TITLE
Edit Log as JSON-LD Activity Stream

### PR DESCRIPTION
**Pull request by benosteen**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
This adds a new view and associated URL handling to allow authenticated clients to get the edit logs regarding the resources managed in Arches, represented as JSON-LD using the Activity Streams 2.0 vocabulary (https://www.w3.org/TR/activitystreams-vocabulary/).

It currently uses the `/history` path, with pages of the activity stream representation available from `/history/1`, `/history/2`, and so on.

Example `/history/` Collection document:

    {
      "@context": "https://www.w3.org/ns/activitystreams",
      "type": "OrderedCollection",
      "id": "http://localhost:8000/history/",
      "totalItems": 7,
      "first": {
        "type": "OrderedCollectionPage",
        "id": "http://localhost:8000/history/1"
      },
      "last": {
        "type": "OrderedCollectionPage",
        "id": "http://localhost:8000/history/1"
      }
    }

Example Collection page (`/history/1`)

    {
      "@context": "https://www.w3.org/ns/activitystreams",
      "type": "OrderedCollectionPage",
      "id": "http://localhost:8000/history/1",
      "partOf": {
        "type": "OrderedCollection",
        "id": "http://localhost:8000/history/"
      },
      "orderedItems": [
        {
          "endTime": "2019-06-20T17:38:56Z",
          "type": "Create",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": null,
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/47b179f0-9382-11e9-b0f5-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:38:57Z",
          "type": "Update",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": "admin",
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/47b179f0-9382-11e9-b0f5-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:39:04Z",
          "type": "Update",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": "admin",
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/47b179f0-9382-11e9-b0f5-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:39:13Z",
          "type": "Create",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": null,
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/514796f2-9382-11e9-9e60-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:39:13Z",
          "type": "Update",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": "admin",
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/514796f2-9382-11e9-9e60-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:39:15Z",
          "type": "Update",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": "admin",
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/47b179f0-9382-11e9-b0f5-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object"
          }
        },
        {
          "endTime": "2019-06-20T17:39:24Z",
          "type": "Update",
          "actor": {
            "url": "http://localhost:8000/user/1",
            "tag": "admin",
            "type": "Person",
            "name": ", "
          },
          "object": {
            "url": "http://localhost:8000/resources/47b179f0-9382-11e9-b0f5-0242ac120003",
            "type": "http://www.cidoc-crm.org/cidoc-crm/E33_Linguistic_Object"
          }
        }
      ]
    }

### Issues Solved

#4938 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by azaroth42** [comment]
A couple of questions: 
 * Is `"name": ", "` a typo in the code, or is the user's name really ", " ?
 * `"tag:" null` shouldn't cause an error, but wouldn't round trip through any processor. Better to leave it out, IMO, unless there's some reason for keeping it?

And a note that in discussing the value of `type` for the `object` of the change, it would be nice to use the data's context, but that might only be locally available in the model definition, and thus generate impossible to process data for external consumers. Thus the decision to use the full URI to the class, even if that stands out as being a little strange with the rest of the otherwise lovely JSON-LD.

**Comment by benosteen** [comment]
The ", " is because the admin user doesn't have a name in the db. The null
is likely a bug from the editlog db - it should be the username of the user
who did the activity. I used tag, as there wasn't a clear way to add in a
username (added because the user uri will not resolve).

**Comment by benosteen** [comment]
Stickler-ci wasn't marking all old lint errors as outdated, so I manually marked the outdated/outdated-but-not-marked-as-such errors as resolved.

**Comment by benosteen** [comment]
Is that an ObjectDoesNotExist error? I'll wrap the section that tries to
pull the resource to get its ontology class to catch that error anyway.

Ben

**Comment by apeters** [comment]
the latest looks good to me.

**Pull request merged**
