### PR TITLE
7128 resource instance filter

### PR DESCRIPTION
**Pull request by apeters**
re #7128

### CODE REVIEW

**Review by chiatt — APPROVED** [review]
Worked as expected for me and the migration ran successfully forward and backward.

**Comment by azaroth42** [comment]
Presentation out of the way, will review tomorrow. Does it fix the branch issue? Also, the %trans for the label on the default value for the card?

**Comment by azaroth42** [comment]
> django.template.exceptions.TemplateSyntaxError: 'compress' is not a registered tag library. [...]

I did a new `pip install -r arches/install/requirements.txt` which found the compressor library ... but something else needs to happen as well?

**Comment by robgaston** [comment]
@azaroth42 see the description of this PR for changes that will need to be applied at the project level for the latest (this will, of course, be included in the next release notes)

**Comment by azaroth42** [comment]
INSTALLED_APPS was the problem. Thanks @robgaston!

**Comment by azaroth42** [comment]
Issues, as discussed on previous call but not filed specifically until now:
* https://github.com/archesproject/arches/issues/7493 
* https://github.com/archesproject/arches/issues/7494

**Review by azaroth42 — CHANGES_REQUESTED** [review]
See: #7493 #7494

**Comment by apeters** [comment]
@azaroth42 can you check the latest fixes for #7493, and #7494

**Comment by azaroth42** [comment]
Yup, confirmed these solve the two issues :) Thanks @apeters !

**Comment by apeters** [comment]
FYI, I'm not going to fix the stickler errors as I think the whitespace improves readability.

**Pull request merged**
