### PR TITLE
Removes full-screen overlay for frontend errors when running webpack development server. #10224

### PR DESCRIPTION
**Pull request by chrabyrd**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Removes full-screen overlay for frontend errors when running webpack development server.

### Issues Solved

#10224

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
Just wondering about the rationale, is it because we demo with the development server?

**Comment by chrabyrd** [comment]
> Just wondering about the rationale, is it because we demo with the development server?

Yes, that and the overlays can be a hinderance for development and don't offer much gain otherwise. It's not surfacing any legitimate errors that don't already appear in the dev console.

**Review by jacobtylerwalls — APPROVED** [review]
Noticed upgrading an Arches implementation to 7.5: without this change (which is okay by me!) we would have needed to increase the lower bound on `webpack-dev-server` to 4.13.0, which is where `runtimeErrors` was introduced.

I almost PR'd that until I realized we're probably just going to merge this instead. LGTM

**Review by chiatt — APPROVED** [review]
Looks good!

**Pull request merged**
