### PR TITLE
2828 add resource method for node value

### PR DESCRIPTION
**Pull request by veuncent**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Forked from PR #2845, expanded with unit tests and exceptions.
 
As per issue #2828 this adds a method on the resource class that provides the ability to get the value of a resource's node based on the node's name.

- Returns a list of values if the name parameter is valid and has at least one value.
- Resolves the Value if the requested node is a concept (currently detects if node value is a UUID).
- Throws `MultipleNodesFoundException` when multiple nodes with the same name are found.
- Throws `InvalidNodeNameException` if the requested node does not exist.

### Checklist

-   [x] Unit tests pass locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

### Further comments

All props go to @bedubs and @mradamcox for writing the initial code.

### CODE REVIEW

**Comment by dwuthrich** [comment]
@veuncent @apeters @chiatt Our Open Issue bot hightlighted this issue as needing a response.  If this issue can be closed, please do so.

**Comment by azaroth42** [comment]
@apeters @chiatt  Can you please review?

**Comment by robgaston** [comment]
this looks okay to merge, but not all contributors have signed the CLA, so I cannot do so at the moment.  it appears that we need a signature from @bedubs

**Comment by bedubs** [comment]
> 
> 
> this looks okay to merge, but not all contributors have signed the CLA, so I cannot do so at the moment. it appears that we need a signature from @bedubs

Shoot, I thought I signed that...maybe since I changed my handle it needs it again? Either way, I'll check that out.

**Comment by mradamcox** [comment]
Thanks @bedubs. I'm sure you signed it before, we just had to reinstall the CLA Assistant app a little while ago, so people had to re-sign it. Thanks for taking the time right now!

**Pull request merged**
