### PR TITLE
7597 accessibility default card 5 2

### PR DESCRIPTION
**Pull request by phudson-he**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Changes have been done to ensure [WCAG 2.1 requirements](https://www.w3.org/TR/WCAG21/#requirements-for-wcag-2-1) have been met for accessibility guidelines.

Details of the changes are as follows:

templates/views/components/cards...

- default-card-report.htm : added aria-labels and made keyboard operable
- default.htm : added aria-labels and made keyboard operable

### Issues Solved
Ensures that components (listed above) conform to accessibility guidelines
#

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @phudson-he
*   Tested by: @phudson-he
*   Designed by: @phudson-he

### CODE REVIEW

**Comment by csmith-he** [comment]
@robgaston @aarongundel There don't appear to be any conflicts between base branch dev/6.1.x and the branch this PR relates to; are you happy to review?

**Review by aarongundel — CHANGES_REQUESTED** [review]
Looks good!  Minor feedback re the knockout event bindings, and it looks like there's an outstanding merge conflict that needs to be resolved.

**Comment by csmith-he** [comment]
@aarongundel - all the keyup events should now be in the viewmodel

**Comment by csmith-he** [comment]
@aarongundel Stickler doesn't seem to like optional chaining (?.) even though it's no different in the ViewModel to how it was in the template.  Is this just an issue with Stickler or an actual issue with the operator?

**Pull request closed without merging**
