### PR TITLE
6930 - Code added to show crosshair when in draw mode

### PR DESCRIPTION
**Pull request by csmith-he**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Changes to the map.js and map-editor.js viewmodels and the map-filter.js view to put the cursor into crosshair mode when drawing geometry as this allows for a more accurate placement of vertices.

### Issues Solved
Cursor wasn't changing to crosshairs when in draw mode

### Checklist
-   [X] Unit tests pass locally with my changes (Only unit tests that failed were to do with v3 to v4 migration and the mobile survey.)
-   [X] Manual testing in local installation to confirm expected behaviour
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by:  Historic England
*   Tested by:  Historic England
*   Designed by:  Historic England

### CODE REVIEW

**Comment by csmith-he** [comment]
@chiatt - Stickler's coming up with a few issues; are they actual problems?

**Comment by chiatt** [comment]
Hi @csmith-he, no need to change 'draw_mode' to camel case, but if you could resolve the indentation errors, that would be great.

**Comment by csmith-he** [comment]
@chiatt - indentation errors fixed.  Only draw_mode errors causing stickler-ci to fail now

**Comment by csmith-he** [comment]
@chiatt I'm going to close this PR and then start afresh as something odd as gone on.

**Pull request closed without merging**
