### PR TITLE
Fixes out of memory issue migrating from 5.2 to 6.2

### PR DESCRIPTION
**Pull request by aj-he**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Issues Solved

#9779 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @aj-he 
*   Tested by: @khodgkinson-he 
*   Designed by: @aj-he

### CODE REVIEW

**Comment by chiatt** [comment]
Hey @aj-he, Just wanted to let you know that this is on my radar and I'll be reviewing it soon.

**Comment by aj-he** [comment]
@chiatt are you ok to merge/cherry pick into 7 branches?

**Comment by chiatt** [comment]
No problem @aj-he. I typically merge changes from the lowest maintained version through the dev branches every few days.

**Comment by aj-he** [comment]
@chiatt - perfect thanks!

**Comment by apeters** [comment]
@aj-he love the use of the iterator here.  Especially makes sense in a migration where one has to typically access every instance of an object.  Thanks for the shout out @chiatt

**Pull request merged**
