### PR TITLE
10838 cbyrd upgrade primevue

### PR DESCRIPTION
**Pull request by chrabyrd**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Issues Solved

#10838

### CODE REVIEW

**Comment by chrabyrd** [comment]
beta.4 causes some heinous webpack issues, so backing off to beta.3 for now

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
If you don't mind, let's go ahead and solve the webpack issue while we're here. I'm showing it's solved with:
```diff
diff --git a/webpack/webpack.common.js b/webpack/webpack.common.js
index 68c779fd84..b5d0d1895b 100644
--- a/webpack/webpack.common.js
+++ b/webpack/webpack.common.js
@@ -305,7 +305,7 @@ module.exports = () => {
                 module: {
                     rules: [
                         {
-                            test: /\.tsx?$/,
+                            test: /\.m?tsx?$/,
                             exclude: /node_modules/,
                             loader: Path.join(PROJECT_RELATIVE_NODE_MODULES_PATH, 'ts-loader'),
                             options: {
@@ -319,12 +319,7 @@ module.exports = () => {
                             loader: Path.join(PROJECT_RELATIVE_NODE_MODULES_PATH, 'vue-loader'),
                         },
                         {
-                            test: /\.mjs$/,
-                            include: /node_modules/,
-                            type: 'javascript/auto',
-                        },
-                        {
-                            test: /\.js$/,
+                            test: /\.m?js$/,
                             exclude: [/node_modules/, /load-component-dependencies/],
                             loader: Path.join(PROJECT_RELATIVE_NODE_MODULES_PATH, 'babel-loader'),
                             options: {
```
(once copied to project template, of course)

**Comment by jacobtylerwalls** [comment]
Taking another look, I may need to retest something before I declare that a success ...

**Comment by jacobtylerwalls** [comment]
Ah, I think I just ran my test case incorrectly. Seems like what changed in the new beta is the .js -> .mjs, which seems like something we might need to handle in our config, but staying on beta3 is fine for now. Approving!

**Review by jacobtylerwalls — APPROVED** [review]

**Comment by chrabyrd** [comment]
Ah yeah there's a webpack workaround but it hits what I believe is [an error in the beta.4 release](https://github.com/primefaces/primevue/issues/5811)

We'll see what they say, but yeah to unblock for now I think merging beta.3 is the way to go 👍 . Will file a ticket for the appropriate webpack tweak.

**Pull request merged**
