### PR TITLE
11179, 11180 search for resource w/o files or geometry

### PR DESCRIPTION
**Pull request by apeters**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Adds the ability to search for resources that have/don't have files or have/don't have geometry as well as the ability to search on file size and geometry type.

re #11179, re #11180

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Comment by whatisgalen** [comment]
this looks like an awesome change. Any chance for fileList advanced search there could be an option for a search criteria of number of files?

**Comment by chiatt** [comment]
The geospatial features work great as does file search when no file is present. However, min and max file size isn't working as expected. In every case I get all documents as if no filter was applied

https://github.com/user-attachments/assets/b40ea107-c121-47b0-9082-ffbf802c9e8e

**Review by chiatt — CHANGES_REQUESTED** [review]
Geospatial and file null search is working as expected. However, file size searches are not. I think that the units are incorrect in the UI, or they need to be converted from mb to kb before the query is performed.

I created two resources - one with a 5.8mb file and one with a 122kb file. I confirmed in the tile data that their sizes were recorded properly. You can see in the video that at 1MB with a greater than search, we should only get the 5.8mb file, but we get both files until the search is increased to 1000mb. 

With a less than search, we get only 1 file at 1000mb, when we should get both if the search was performed in MB. If the search is performed in KB, then the result would make sense.

https://github.com/user-attachments/assets/dde56a4d-4df7-4d09-a7ba-6ebc606b43b4

**Review by chiatt — APPROVED** [review]

**Comment by chiatt** [comment]
> this looks like an awesome change. Any chance for fileList advanced search there could be an option for a search criteria of number of files?
> 
> I think you could do it with these changes in `datatypes.py` at line 1308:
> 
> ```python
> def append_to_document(self, document, nodevalue, nodeid, tile, provisional=False):
>         try:
>             for f in tile.data[str(nodeid)]:
>                 val = {
>                     "string": f["name"],
>                     "nodegroup_id": tile.nodegroup_id,
>                     "provisional": provisional,
>                 }
>                 document["strings"].append(val)
>             file_ct_val = {
>                "number": float(len(tile.data[str(nodeid)])),
>                 "nodegroup_id": tile.nodegroup_id,
>                 "provisional": provisional,
>             }
>             document["numbers"].append(file_ct_val)
> ```
> 
> And at line 1692:
> 
> ```python
>  def get_es_mapping(self, nodeid):
>         ret = {
>             "properties": {
>                 "tiles": {
>                     "type": "nested",
>                     "properties": {
>                         "data": {"properties": {str(nodeid): self.default_es_mapping(), "file_count": {"type": "double"}}},
>                     },
>                 }
>             }
>         }
>         return ret
> ```
> 
> And at line 1304:
> 
> ```python
> if value["op"] == "gte" or value["op"] == "lte":
>     operators = {"gte": None, "lte": None, "lt": None, "gt": None}
>     operators[value["op"]] = float(value["val"]) * 1000
>     search_query = Range(
>         field="tiles.data.%s.size" % (str(node.pk)), **operators
>     )
>  elif value["op"] == "eq":
>     field_path = "tiles.data.file_count"
>     search_query = Terms(**{field_path: float(value["val"])})
> ```
> 
> And then on the frontend:
> 
> in `file-list.htm` (change at line 13):
> 
> ```
> select2Config:{
>                 data: [
>                     { text: $root.translations.sizeGreaterThan, id: 'gte' },
>                     { text: $root.translations.sizeLessThan, id: 'lte' },
>                     { text: $root.translations.hasNoValue, id: 'null' },
>                     { text: $root.translations.hasAnyValue, id: 'not_null' },
>                     { text: $root.translations.hasNumberOfFiles, id: 'eq' },
>                 ],
>                 value: op,
> ```
> 
> and in `javascript.htm` (change at line 336):
> 
> ```
> has-number-of-files='{% trans "Has number of files" as hasNumberOfFiles %} "{{ hasNumberOfFiles|escapejs }}"'
> ```

I think this is a good suggestion, but it should probably be an issue for v8.

**Pull request merged**
