### PR TITLE
Add check for published graph in every system language #10079

### LINKED ISSUE #10079: Resource editor raises KeyError when switching languages
1. Enable ~the language switcher~ an additional language
2. Save a new resource ~model~ instance
3. Change to that language

```py
Internal Server Error: /resource/44490b12-feb3-4b09-977c-8b15588baea4
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/web_root/arches/arches/app/utils/decorators.py", line 82, in wrapper
    return function(request, *args, **kwargs)
  File "/web_root/arches/arches/app/views/resource.py", line 277, in get
    serialized_graph = published_graph.serialized_graph
AttributeError: 'NoneType' object has no attribute 'serialized_graph'
```

Tested with afs
Version 7.5 dev

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Helpfully fail with a system check and a hint if adding system languages without having republished graphs yet.

### Issues Solved

Closes #10079

### Checklist

-   I targeted one of these branches:
    - [x] dev/8.0.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by chrabyrd — COMMENTED** [review]
I like it, but the branch this is in theory replacing is targeting dev/7.6.x. Could you rebase?

**Comment by jacobtylerwalls** [comment]
Can do with a blessing from @chiatt (assuming I figure out why this chokes on CI)

**Comment by jacobtylerwalls** [comment]
Also I need to check the sets differently, having more publications is fine.

**Comment by jacobtylerwalls** [comment]
Had to fix some unrelated weaknesses to get this over the line -- probably too hot for 7.6 at this point.

**Comment by chrabyrd** [comment]
> Had to fix some unrelated weaknesses to get this over the line -- probably too hot for 7.6 at this point.

Fair 👍 . How do you feel about having https://github.com/archesproject/arches/pull/11342 merged into 7.6 to handle the error, with it undone/redone in this branch targeting 8.0?

**Comment by jacobtylerwalls** [comment]
Setting to draft while @aarongundel looks at the permissions bugs that this exposed. Then I'll rebase after we trickle that up to 8.0.

**Review by chrabyrd — APPROVED** [review]
🚀

**Pull request merged**
