### PR TITLE
Improve error handling 

### PR DESCRIPTION
**Pull request by veuncent**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

This PR improves error handling by preventing uncaught errors (most importantly `TypeErrors` caused by `response.responseJSON` being undefined). 

- A new viewmodel `JsonErrorAlertViewModel` was added to parse `responseJSON` and use the (global) default error title and message if it is `undefined`.

- Viewmodels were updated to use this new `JsonErrorAlertViewModel`.

- Views were updated to return errors in a more standardized way using `JSONErrorResponse` (inherits from regular `JSONResponse`).

### Issues Solved

#4212 --> Most importantly, this solves problems where the Arches app did not get the chance to return a response, e.g. in the case of a web server timeout. This causes `response.responseJSON` to be `undefined`, while Arches' `alert` mechanism relies heavily on this object. 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by chiatt** [comment]
Hi @veuncent - This looks like really nice work. Would you like somebody to review it? If so, would you be able to resolve the conflicts first?

**Comment by veuncent** [comment]
Yes please! :)
I'll need to find time to resolve the conflicts, because I'm working
full-time now. Hopefully this weekend.

**Comment by veuncent** [comment]
I solved the merge conflicts. Please review before new conflicts arise :)

Thanks @chiatt !

**Comment by veuncent** [comment]
Thanks for the merge @chiatt ! 
Should the stickler issues still be resolved? I didn't get the chance to fix them.

**Pull request merged**
