### PR TITLE
Respond to invalid api routes with JSON #11166

### LINKED ISSUE #11166: Nonexistent api routes respond with HTML instead of JSON
- Visit an invalid api route

**Result**: Django debug page (or "Not Found" template if DEBUG = False)
**Expected**: JSON payload
***
The Django debug page is great for development, because it lists routes to aid in debugging. But if you/your application visits an invalid route, I'm suggesting it would be better to return JSON that is parsable by the frontend.

For example, I think this:

json-response

... would be preferable to this (current):

html-response

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
A client might issue a malformed URL, e.g. api/controlledlists/1, which is malformed because 1 is not a UUID. It would be better for the server to respond with a JSON payload that could be parsed without additional effort. See screenshots on issue.

### Issues Solved

Closes #11166

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: Getty Conservation Institute
*   Found by: @jacobtylerwalls
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Comment by apeters** [comment]
@jacobtylerwalls I'm not sure how to test this.  I can see that we now have an endpoint at "api", but how would this be used in practice?

**Comment by apeters** [comment]
> So you can visit any invalid api route like `api/garbage` and ensure you get JSON back instead of the Django debug page. JSON is obviously much easier to parse into an error message, see screenshots on #11166 of this working in a vue app.

I tried this but got a 400 htm error page instead of JSON
Screenshot 2024-08-07 at 7 06 38 PM

**Comment by jacobtylerwalls** [comment]
I can't reproduce. Is there any additional information in the response?

**Comment by jacobtylerwalls** [comment]
I can only get a response like that if I have DEBUG=False and a bad value in ALLOWED_HOSTS.

But you don't need to test with DEBUG=False. Testing with DEBUG=True is easy because you can verify that you _do not_ get the url debug view, but rather the route matches and returns JSON.

**Review by apeters — APPROVED** [review]
looks good!  Thanks for the explanation @jacobtylerwalls !

**Pull request merged**
