### PR TITLE
Fix "sortorder" values are not being preserved during a JSON import

### PR DESCRIPTION
**Pull request by jkemper-pca**
When a json file is used for the `import_business_data` command, the "sortorder" values are not being used and all tiles are resetting to all be "sortorder: 0".

### Example

1. Initial Manual Data Entry
*Note the order and the resource name at the top*
Fixed_Report
[Initial_Export.json which is used for all `import_business_data` commands](https://github.com/archesproject/arches/files/15204092/Initial_Export.json)
1. After using `export_business_data` followed by `import_business_data`
*Note the same areas as last step are now in an incorrect order (this is not a consistent order but is random each time)*
Reimported_Report
[Reimported_Export.json](https://github.com/archesproject/arches/files/15204094/Reimported_Export.json)
1. After adding the fix and running `import_business_data` on the same data file as the previous step
*This has the same order as the original data*
Fixed_Report
[Fixed_Export.json](https://github.com/archesproject/arches/files/15204095/Fixed_Export.json)

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
This change adds one line to ingest code for a JSON import and gets the supplied "sortorder" value for a tile similar to how it gets values for "nodegroup_id", "parenttile_id", etc.

### Issues Solved
Now, JSON data that is imported will maintain its order.
#

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Parks Canada
*   Found by: @jkemper-pca 
*   Tested by: @jkemper-pca 
*   Designed by: @jkemper-pca

### CODE REVIEW

**Review by whatisgalen — CHANGES_REQUESTED** [review]
I suspect it isn't breaking the tile save, but I imagine we want sortorder to be cast to `int()` instead of `str()`

**Review by whatisgalen — APPROVED** [review]
looks good!

**Comment by whatisgalen** [comment]
@jkemper-pca thanks for submitting this PR! In the future, you can first create an "Issue" and then in a Pull Request specify "Issues Solved: #[number of the issue]" that way others can comment if it's something they might already be working on or if there's more to the problem than meets the eye.

**Comment by mradamcox** [comment]
Just encountered this issue on an old 6.2.0 branch. Thanks for finding and fixing it!

**Pull request merged**
