### PR TITLE
Handle deletion verify at card component level #9091

### PR DESCRIPTION
**Pull request by khodgkinson-he**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

User Verification alert added to prevent the user accidentally deleting a card.

### Issues Solved

#9091

### CODE REVIEW

**Comment by chiatt** [comment]
Hi @khodgkinson-he, is this PR ready for review?

**Comment by khodgkinson-he** [comment]
Hello @chiatt , my apologies for the delay in getting back to you on this one..

Yes indeed, I think this is ready for review, (though we may want to change the merge target branch to something more up to date).  I've tested the fix against a branch from our current 'dev/7.4.x' fork, and don't anticipate any issues.. 

Happy to raise a fresh PR if that'd be easier..  ^_^

**Comment by khodgkinson-he** [comment]
Good Morning @chiatt,

  as you can see form the above I've had a look at changing the base branch, got spooked, and backed away again..  ^_^

  ..please let me know if you'd like me to cherry-pick this onto a fresh copy of our dev/7.4.x fork!

**Comment by khodgkinson-he** [comment]
@chiatt @aj-he : Please Note this PR has now been rebased to dev/7.5.x - Anything else I can do to help, please let me know!  ^_^

**Review by chiatt — CHANGES_REQUESTED** [review]
@khodgkinson-he Sorry I didn't get this into 7.4. I intended to, but I just ran out of time. 
I have just a couple of suggestions. 

The first is that a user can work around this if the card's cardinality is n by clicking here:
image

It would be good to fire the alert there as well. 

The second issue is that because it's in 7, it should support internationalization. To do that in JavaScript, you can add new translation strings in javascript.htm like this: https://github.com/archesproject/arches/blob/03b0b1d6211004fd353952a07473ed52652f00ad/arches/app/templates/javascript.htm#L123

Then in the code you'd reference your translation like this (notice the snake case becomes camel case):

```
new AlertViewModel(
    'ep-alert-red',
    arches.translations.confirmResourceDelete.title + `: ${self.card.model.name()}`,
    arches.translations.confirmResourceDelete.text + `: ${self.card.model.name()}`,
```

It might be nice if instead of 'Item' the actual name of the card was used. You can get that string from self.card.model.name(). Then you can do something very targeted to the card. For a card called `Name of Place`, it might be something like:  
```
Name of Place Deletion
Are you sure you would like to delete this Name of Place?
```
This would have the advantage of adding a very generic translation for deletions that could be used elsewhere in the application. 

What do you think?

**Comment by khodgkinson-he** [comment]
Hi @chiatt, (no worries sir.. ^_^)

  I think those sound like excellent enhancements to me.

**Review by chiatt — APPROVED** [review]
Looks good!

**Pull request merged**
