### PR TITLE
9147 - fix i18n bug in __arches_get_tile_cardinality_violations

### PR DESCRIPTION
**Pull request by bferguso**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Fix i18n bug in __arches_get_tile_cardinality_violations - was referring to graphs.name as text, not i18n JSON string.

### Issues Solved

#9147 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @bferguso
*   Designed by: @bferguso

### Further comments
I've added a diff here - copied the new function to the reverse migration section to show the diff.:
https://github.com/bcgov/arches/compare/9147_tile_cardinality_function_bug...bcgov:arches:9147_diff?expand=1

### CODE REVIEW

**Review by apeters — CHANGES_REQUESTED** [review]
Hard coding "en" as the language will break if that language doesn't exist.  Maybe the function should allow users to enter the language code as an argument to the function.  

It doesn't look this function isn't called anywhere, but instead it's left up to users to call it instead.  Is that right?

**Comment by bferguso** [comment]
@apeters - I actually meant to leave a comment about this. I had originally added i18n config to this, but I was a bit confused about the difference in the graph.name i18n JSON structure and the structure everywhere else. Everywhere else the i18n JSON structure is something like 
`{'en': {'value': '[data]', 'direction': '[direction]'}, 'de': {}....}`
What I'm seeing in the graph.name column is just 
`{'en': '[en name]'}`. Wondering why the difference in the structure there, and wasn't sure what the intent was. I was originally pulling the language with `select code from languages where isdefault limit 1;`

This function is called by the `__arches_complete_bulk_load()` function which re-enables the tile validation triggers and checks to ensure there are no tile cardinality issues that were caused when they were disabled for data loading. It is only called by users directly if they use this mechanism for loading data via the views.

**Comment by bferguso** [comment]
@apeters - Are you OK if we just use the default language instead of requiring the user to pass it in as a parameter? I've made a change for that if it's an acceptable option.

**Review by apeters — APPROVED** [review]
users will need to remember to make sure the default language in the languages table is in sync with the setting in settings.py

**Pull request merged**
