### PR TITLE
10381 celery file size threshold

### PR DESCRIPTION
**Pull request by whatisgalen**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

copy of #10382 but into `dev/7.6.x`

### Issues Solved

#10381

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Comment by whatisgalen** [comment]
fyi @chiatt

**Review by njkim — COMMENTED** [review]
@whatisgalen This looks good.
One thing, can we make the default 500 the same as the original?

**Comment by whatisgalen** [comment]
> @whatisgalen This looks good. One thing, can we make the default 500 the same as the original?

Just pushed that change! Thanks!

**Comment by njkim** [comment]
Looks good, thanks. Sorry taking so long.

**Pull request merged**
