### PR TITLE
9342/9493 Make map widget & search map filter accessible

### PR DESCRIPTION
**Pull request by johnatawnclementawn**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Improve accessibility of map widget and its configuration.

### Issues Solved

#9342

### CODE REVIEW

**Review by apeters — COMMENTED** [review]
the coordinate editor needs to be made accessible
Screenshot 2023-06-22 at 3 17 02 PM

**Review by apeters — CHANGES_REQUESTED** [review]
Clicking the "Add Buffer" link should set the focus to the "Distance" stepper.
Screenshot 2023-06-23 at 12 05 46 PM

**Comment by johnatawnclementawn** [comment]
> Clicking the "Add Buffer" link should set the focus to the "Distance" stepper. Screenshot 2023-06-23 at 12 05 46 PM

@apeters, per our conversation I think we can address this in #9723 once this PR has been QA'd and merged

**Review by apeters — APPROVED** [review]
looks good to me

**Pull request merged**
