### PR TITLE
filter hidden nodes

### PR DESCRIPTION
**Pull request by aarongundel**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Adds new feature to filter nodes based on card "visible" attribute.  

### Issues Solved

#7838 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Comment by aarongundel** [comment]
@chiatt I added this to the bulkdisambiguatedresourceinstance endpoint under the hidden=false parameter.  Let me know if there are other places I should add this.

**Review by chiatt — CHANGES_REQUESTED** [review]
This looks really good, but `resource.to_json` is called in the api.Resources.get method as well. The hidden property will need to be passed in there too.

**Comment by aarongundel** [comment]
Thanks for pointing that out @chiatt - I've corrected that and simplified some variable parsing logic.

**Review by chiatt — APPROVED** [review]
Looks good to me!

**Pull request merged**
