### PR TITLE
11080 chunk es geometries

### LINKED ISSUE #11080: Allow geometries that are > 32k in size
There currently no way to create large geometries that produce an ES document > 32k. Strategies such as simplifying the geometry or reducing the precision of the coordinates have been used to fit large geometries into the 32k Lucene limitation, however this does not always reduce the size enough, and can cause search discrepancies near the geometry boundary.

Perhaps larger geometries can be broken down into smaller chunks and uploaded as individual documents in the ES geometries document array to allow for arbitrarily large geometries to be created or uploaded into Arches..

### PR DESCRIPTION
**Pull request by bferguso**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

This allows geometries to be created if they are larger than the 32k Lucene index document limit.

### Issues Solved

Closes #11080 

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @ 
*   Designed by: @bferguso

### Further comments
This was working against my dev/7.5.x, but is untested against dev/7.6.x and is for review/discussion.
This is a rough first cut.

### CODE REVIEW

**Comment by chiatt** [comment]
I was able to get a really large geometry (20k vertices at 689576 bytes) to be split into chunks. I expected to get about 20 chunks, but I only got 2. I don't think this is a problem. I suspect it was because my geometries are really just simple rectangles with lots of vertices along each side. I guess postgis ignored those redundant points when splitting.  In any case, both 'chunks' were being indexed. However, when I perform a spatial search, I don't get any search results. 

image

I inspected the chunks and they appear to be valid geometries
image

Here's my data if you'd like to test:
[biggeo.json.zip](https://github.com/user-attachments/files/16005421/biggeo.json.zip)

**Comment by bferguso** [comment]
@chiatt - I'll see if I can find time to spin up a 7.6.x version to try to debug this PR on that version. I've only had it working on 7.5.x here as that's what I'm developing our apps on.

**Comment by chiatt** [comment]
> @chiatt - I'll see if I can find time to spin up a 7.6.x version to try to debug this PR on that version. I've only had it working on 7.5.x here as that's what I'm developing our apps on.

Thanks @bferguso, I'll test the 7.5.x PR as well.

**Review by chiatt — CHANGES_REQUESTED** [review]
This is looking really good @bferguso - Just a few things that are now unused with these changes. Could you remove the reduce_precision method in geo_utils: https://github.com/archesproject/arches/blob/0fcc6e46c8649d4d9817f78b94beca75c0af7153/arches/app/utils/geo_utils.py#L97

Also, `max_bytes`, `byte_count`, and `byte_count += len(str(value).encode("UTF-8"))`
https://github.com/archesproject/arches/blob/0fcc6e46c8649d4d9817f78b94beca75c0af7153/arches/app/datatypes/datatypes.py#L1175-L1177

**Comment by bferguso** [comment]
@chiatt - Thanks for pointing those out. Unused method and variables removed.

**Review by chiatt — APPROVED** [review]

**Pull request merged**
