### PR TITLE
change to firefox compatible event properties

### PR DESCRIPTION
**Pull request by mradamcox**
modify two functions so that firefox can interpret the pixel position correctly.

### CODE REVIEW

**Comment by mradamcox** [comment]
also, this should close [issue 270](https://github.com/archesproject/arches/issues/270), but I'm not sure if there's an automated way to do that.

**Comment by mradamcox** [comment]
So I'm not sure why the travis tests failed, I've only just learned about what Travis CI is.  I only changed a few, non-build-related lines, so does that mean these tests will fail on every pull request?

**Comment by apeters** [comment]
Hi Adam,
We have a couple of tests that are failing at the moment that aren't
related (as far as I know) to what you pushed.   Any time you push it
triggers a build.  Until we fix those 2 tests it will always fail.
So, I wouldn't worry.
Cheers,
Alexei


Director of Web Development - Farallon Geographics, Inc. - 971.227.3173

**Comment by mradamcox** [comment]
Ok, that's what I was thinking, just wanted to double-check.

**Pull request merged**
