### PR TITLE
Fix multiple semantic nodes in branch parent tile issue

### PR DESCRIPTION
**Pull request by azaroth42**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)

### Description of Change

Change the JSON-LD parser to assign the parenttile_id based on the tile in `result` (being definitely the parent tile passed in from the previous recursion) rather than the previous tile from the loop, which might be a tile further down a branch when longer chains of branches are compacted into a single card / tile.

### Issues Solved

#6235 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by azaroth42** [comment]
Ping. Please review and merge.

**Comment by azaroth42** [comment]
Bump. Please merge.

**Comment by azaroth42** [comment]
Should have a test. @azaroth42 to add one and ping @apeters to merge.

**Comment by azaroth42** [comment]
Added test that fails in master and passes in this branch. Tagging back to @apeters for review and merge.

**Comment by azaroth42** [comment]
These tests fail in master, nothing to do with this PR. Handing back :)

**Comment by apeters** [comment]
fixed in the latest

**Comment by azaroth42** [comment]
The issue isn't fixed in master. Reopening the PR.  #6440 depends on this one, but doesn't have the test.

**Pull request merged**
