### PR TITLE
6492 advanced search datetime

### PR DESCRIPTION
**Pull request by njkim**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

The time format to add ES search query for advanced search is modified to include the time zone to properly indexed for the search, and  also the support for the time format is added. re #6492 

### Issues Solved

Fixed the error in the advanced search for the card that is datetime data type.

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by chiatt — COMMENTED** [review]
@njkim I think what you've done is really good, but as you had observed - because the date format was hardcoded with the time in the date datatype search html, we had to always search with a time from advanced search (so if the value was `2000-01-01` advanced search would query `2000-01-01 00:00:00-07:00`. The problem with that is that the data was indexed without a time, so ES assumed the date was in UTC. That meant to search for a date, you had to make sure that the local time was adjusted to local time equivalent of UTC. 

To get around this problem it became clear that we needed to be able to configure the date format at the node/datatype rather than the widget. I went ahead and made that change. I think the date format belongs on the node because it affects how the data is stored on the node.

Because these changes are pretty significant, I'm going to pass this onto @apeters for review both of our changes.

**Comment by chiatt** [comment]
To QA:
1. run migrations
2. create a two date nodes, one with a 'YYYY-MM-DD' format and the other with 'YYYY-MM-DD HH:mm:ssZ'. 
3. create some tile data for each node
4. in advanced search confirm that you can find your resource by searching on the tile data you created in step 2.

**Review by apeters — CHANGES_REQUESTED** [review]
It looks like time is enabled in the search widget, but it is ignored and not sent to the sever.  We should either allow users to include time in their search, or remove the ability to specify time in the search widget.

Everything else looks good.!

**Review by apeters — APPROVED** [review]
this now works as expected

**Pull request merged**
