### PR TITLE
fixes get_child_edges sql injection #9026

### PR DESCRIPTION
**Pull request by chrabyrd**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

fixes sql injection in concept model `get_child_edges` method

### Issues Solved

#9026

### CODE REVIEW

**Review by apeters — CHANGES_REQUESTED** [review]
this will still fail because of the string formatting done with the "subquery".

@chrabyrd ask my about a url to test this.

Looking at this more closely, it looks like we can incorporate the "subquery" into the full "sql" string variable.  I don't think we need it.  Then we can just pass the "query" concatenated with leading and trailing "%%" as a param to cursor.execute.

**Comment by chrabyrd** [comment]
@apeters yeah we should chat. Re-interpolation failed for me for queries without a subquery

**Comment by chrabyrd** [comment]
I re-ran the results from my branch and status quo through a diff checker: 

the query `http://localhost:8000/concepts/paged_dropdown?conceptid=e480165f-44d2-4ec4-b13a-f246270f06af` results in: https://www.diffchecker.com/bSunlEME

the query `http://localhost:8000/concepts/paged_dropdown?conceptid=e480165f-44d2-4ec4-b13a-f246270f06af&query=art` results in: https://www.diffchecker.com/UJX5fUY4

**Review by apeters — APPROVED** [review]
works great!

**Pull request merged**
