### PR TITLE
Update the logic to get cardwidgets for editor, #8861

### PR DESCRIPTION
**Pull request by njkim**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Update the logic to get cardwidgets when serialized graph isn't available. #8861 

### Issues Solved

#8861

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by chiatt — APPROVED** [review]
Looks good!

**Comment by ekansa** [comment]
@chiatt I'm getting a new problem with this.  The Django server says:
```
aher7-0                 | Internal Server Error: /en/graph/8ec7cd9d-e7fd-4e59-abd5-dcd25cca06dd/append_branch
aher7-0                 | Traceback (most recent call last):
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
aher7-0                 |     return self.connection.commit()
aher7-0                 | psycopg2.errors.ForeignKeyViolation: insert or update on table "nodes" violates foreign key constraint "nodes_nodegroupid_30e98973_fk_node_groups_nodegroupid"
aher7-0                 | DETAIL:  Key (nodegroupid)=(82b46dae-2589-11ed-80ef-0242ac130005) is not present in table "node_groups".
aher7-0                 |
aher7-0                 |
aher7-0                 | The above exception was the direct cause of the following exception:
aher7-0                 |
aher7-0                 | Traceback (most recent call last):
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
aher7-0                 |     response = get_response(request)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
aher7-0                 |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
aher7-0                 |     return self.dispatch(request, *args, **kwargs)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
aher7-0                 |     return handler(request, *args, **kwargs)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
aher7-0                 |     return bound_method(*args, **kwargs)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
aher7-0                 |     return view_func(request, *args, **kwargs)
aher7-0                 |   File "/web_root/arches/arches/app/views/graph.py", line 380, in post
aher7-0                 |     graph.save()
aher7-0                 |   File "/web_root/arches/arches/app/models/graph.py", line 529, in save
aher7-0                 |     self._nodegroups_to_delete = []
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/transaction.py", line 246, in __exit__
aher7-0                 |     connection.commit()
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
aher7-0                 |     return func(*args, **kwargs)
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
aher7-0                 |     self._commit()
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
aher7-0                 |     return self.connection.commit()
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
aher7-0                 |     raise dj_exc_value.with_traceback(traceback) from exc_value
aher7-0                 |   File "/root/.local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
aher7-0                 |     return self.connection.commit()
aher7-0                 | django.db.utils.IntegrityError: insert or update on table "nodes" violates foreign key constraint "nodes_nodegroupid_30e98973_fk_node_groups_nodegroupid"
aher7-0                 | DETAIL:  Key (nodegroupid)=(82b46dae-2589-11ed-80ef-0242ac130005) is not present in table "node_groups".
aher7-0                 |
aher7-0                 | [26/Aug/2022 16:53:27] "POST /en/graph/8ec7cd9d-e7fd-4e59-abd5-dcd25cca06dd/append_branch HTTP/1.1" 500 153203
```
And the front end says "Request Failed...
Sorry! The request failed. Please try again. Contact your system administrator if the problem persists."

This is when I try to associate a branch that I made with a resource model using the Graph Designer.

**Comment by robgaston** [comment]
@ekansa I suspect this comment is unrelated to this pull request.  I came across this bug as well, and I don't think this is new, as it is being caused by a previously existing uniqueness constraint on node aliases (ticket opened, #8878).  You probably are adding a branch with node aliases that conflict with the resource model you are adding it to.  If you try with a branch that does not have conflicting node aliases I think you will see that the original issue w/ appending branches is now resolved.

**Comment by ekansa** [comment]
@robgaston OK thanks! I'll give that a try!

**Pull request merged**
