### PR TITLE
9101 - Check for null currentValue before trying to set i18n value

### PR DESCRIPTION
**Pull request by bferguso**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Rich Text widget fix for null currentValue JSON value

### Issues Solved

#9101 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @bferguso
*   Designed by: @bferguso

### CODE REVIEW

**Comment by bferguso** [comment]
Updated this PR to set default currentValue, using the same pattern as used in the currentDefaultValue in these widgets.

**Comment by apeters** [comment]
@bferguso there's a simple merge conflict that needs to be fixed.  I fixed it locally, but I can't push back to your branch.  Can you fix it?

This line was subsequently added to rich-text.js

```self.card = params.card;```

**Comment by bferguso** [comment]
Hi @apeters - I took a clean, current cut of dev/7.2.x, cherry picked my changes and force pushed back up to this branch so it should be good to go now.

**Review by apeters — APPROVED** [review]
works as expected

**Pull request merged**
