### PR TITLE
Feat: Workflow Builder

### PR DESCRIPTION
**Pull request by teenorth**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Issues Solved

Closes #

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @teenorth 
*   Designed by: @teenorth 

### Further comments

Some further discussions might be need around `arches/app/views/workflow_builder.py`. I originally put this file together to allow me to get better access to configuring plugins but I might have re-implemented existing work so please let me know if there's anything that can be changed.

If you're interested the `workflow_builder.py > class WorkflowBuilderCardOverride` endpoints contains the card endpoint override for workflow component abstracts. This endpoint will create fake parent tiles to trick the workflow component abstracts into loading all available card widgets so they can be seen from the editor.

Apologies I couldn't get this PRed sooner, been busy :D

### CODE REVIEW

**Comment by chiatt** [comment]
Thanks @teenorth - I'm very much looking forward to this functionality. It seems to me, though, that this should be designed as an Arches App rather than a feature added directly to core. This makes sense in part because workflows are not needed for many projects (if workflows themselves were introduced today, they too would be an app). Also, as an app the workflow builder could be maintained outside of the Arches release cycle. I'm not sure how others feel though. @chrabyrd?

**Comment by chrabyrd** [comment]
@chiatt very much agreed. In a perfect world I'd argue workflows themselves should be pulled into the same application, but that's very likely out of scope

**Comment by aj-he** [comment]
@teenorth - I know a number of people who will be excited by this! One thing that is important is the need to ensure that new things being added to Arches, or could become an expected tool for Arches that use a core feature, are accessibility compliant.

You for example, you need to ensure that the UI can be navigable by keyboard, provide aria attributes for screen readers, text flow and resizing.

The move to PrimeVue/Vue.js will add all of this to the existing editing and authoring tools, and should be part of any Arches Application that could be considered by system implementers as core.

Start by using a Chrome plugin such as Wave or ArcToolkit. That should help guide you.

**Comment by whatisgalen** [comment]
@chiatt @chrabyrd is there any reason we can't stub out workflows as a standalone application and separate repo under archesproject so that @teenorth can move this PR there?

**Comment by chiatt** [comment]
> @chiatt @chrabyrd is there any reason we can't stub out workflows as a standalone application and separate repo under archesproject so that @teenorth can move this PR there?

@teenorth wouldn't actually need to wait for that. He could create an app that is just the workflow builder that will work with 7.6.

**Comment by chiatt** [comment]
Closing as the Workflow Builder will be moved to its own repository under archesproject as an app.

**Comment by taylorn01** [comment]
@chiatt I completed some documentation for the workflow builder to help assist non technical users to begin using the builder. It was requested by our team but I've left it open for anyone. Here's the google drive link to the pdf https://drive.google.com/file/d/1o4Wf5sAXrsIc0a2MpZexdwHrZwVkWxjU/view?usp=drive_link

**Pull request closed without merging**
