### PR TITLE
9145 Fix for the visual edit coordinates bug with multiple coordinates in a polygon 

### PR DESCRIPTION
**Pull request by SDScandrettKint**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
CSS fixes for the bug that caused the Edit Coordinates panel to be crammed with coordinates for a polygon with many coordinates.

### Issues Solved

#9145 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Knowledge Integration
*   Found by: @SDScandrettKint
*   Tested by: @SDScandrettKint
*   Designed by: @SDScandrettKint

### CODE REVIEW

**Review by chiatt — COMMENTED** [review]
This solution fixes the problem in the default card. However, because it changes the `workbench-card-sidepanel` class, it is bound to have impacts on other workbench implementations. To avoid this problem, a solution to this bug will need to only change classes/html related to the map coordinate editor itself.

A step in the right direction would be a change like this, which will allow the coordinates to scroll:
```
.map-coordinate-editor-list {
    padding: 0 5px;
    margin-top: 70px;
    height: 300px;
    overflow-y: auto;
}
```
This is not a complete solution because hard-coding the height here will constrain the height in the Map Card.

**Comment by chiatt** [comment]
@SDScandrettKint - I see that #9145 is closed? Is it resolved without this PR?

**Comment by SDScandrettKint** [comment]
> @SDScandrettKint - I see that #9145 is closed? Is it resolved without this PR?

Sorry, I saw there was a closed duplicate issue and presumed it had been resolved! I've reopened the issue and will begin looking into it again.

**Comment by SDScandrettKint** [comment]
I tried to update this PR branch to dev/7.4 without realising it's old and was originally intended to be merged into dev/6.2.x, therefore I've closed the PR and will create a new one into dev/7.4.x.

**Pull request closed without merging**
