### PR TITLE
10351 fix report no scroll

### PR DESCRIPTION
**Pull request by apeters**
re #10351

### CODE REVIEW

**Comment by jacobtylerwalls** [comment]
If I'm looking at the right place, then I too don't see a horizontal scroll:

report-small-width

**Comment by apeters** [comment]
@jacobtylerwalls this was supposed to fix a vertical scroll issue, I didn't look into horizontal scroll

**Comment by jacobtylerwalls** [comment]
@apeters Ah, sorry. Do you recall how to reproduce the original problem without this change, then?

**Comment by apeters** [comment]
@jacobtylerwalls well, any longish report (that flows beyond the bottom of the page) shouldn't be able to be scrolled.  sometime if you don't hide the null values in a report, then it becomes long enough to see the issue.

**Comment by jacobtylerwalls** [comment]
Will take a quick peek at arches-for-science, since there's an [extra `!important` over there](https://github.com/archesproject/arches-for-science/blob/a98815b8f248ca477562c910a06786830e31d1b0/arches_for_science/media/css/report_templates.css#L1-L5)

**Review by jacobtylerwalls — APPROVED** [review]
Looks great. I'll follow-up with the same change in AfS.

**Pull request merged**
