### PR TITLE
Graph editing workflow - redirecting users to the most suitable page 

### PR DESCRIPTION
**Pull request by chiatt**
re #1129 

### Description of Change
Redirecting users to the most suitable graph page when switching between pages in the graph designer.

### QA Checklist

Graph Designer:
- [ ] When at the graph designer switching to another graph navigates to the other graph's designer

Settings:
- [ ] When at the graph settings switching to another graph navigates to the other graph's settings

Cards:
- [ ] When at the card manager switching to another graph navigates to the other graph's card manager
- [ ] When at the card configuration manager switching to another graph navigates to the other graph's card configuration manager at their root card. 

Menus:
- [ ] When at the menu manager switching to another resource model navigates to the other resource model's menu manager
- [ ] When at the menu manager switching to a branch navigates to the branch's settings page

Reports
- [ ] When at the report manager switching to another resource model navigates to the other resource model's report manager
- [ ] When at the report editor switching to a resource model navigates to the other resource model's report manager page
- [ ] When at the report editor switching to a branch navigates to the branch's settings page
- [ ] When at the report manager switching to a branch navigates to the branch's settings page.

Functions:
- [ ] When at the function manager switching to another resource model navigates to the other resource model's function manager
- [ ] When at the function manager switching to a branch navigates to branch's settings page.

Permissions:
- [ ] When at the permissions manager switching to another resource model navigates to the other resource model's permissions manager
- [ ] When at the permission manager switching to a branch navigates to branch's settings page.

### CODE REVIEW

**Comment by dwuthrich** [comment]
@chiatt When at a card manager initial page (e.g.: showing card tiles) for a resource model, switching to a branch should navigate to the card editor page (not, as currently implemented, the card manager initial page)

**Comment by apeters** [comment]
@chiatt I noticed one other thing.  
- When switching between resource graphs in the card configuration manager it seems like we should just go to the card manager itself instead of going to the `root card` of the other resource graph.  It just seems to be a bit of a crap shoot what card you end up getting.  Eg. if there are 10 cards then it's probably a 1 in 10 chance of getting the card you want.  In fact this is what happens with the menu manager.  If editing a specific menu in one resource graph and then switching to another resource graph you go to the menu manager, not a specific menu.

**Comment by chiatt** [comment]
@apeters I agree, but when I went to add an exception hander in the CardView for cases when the cardid was actually a graphid, I found that there was already code that handled for that case and it directed the user to the card configuration page rather than the card manager. I wasn't sure why that was there, so I decided not to change it.

**Comment by chiatt** [comment]
@dwuthrich @apeters 

I've made both changes to card manager/ configuration navigation.  In a nutshell the navigation follows this pattern:

model > branch = card configuration manager
model > model = card manager
branch > model = card manager
branch > branch = card configuration manager 

I updated the checklist for cards in the QA checklist above.

**Comment by apeters** [comment]
meets requirements

**Pull request merged**
