### PR TITLE
add load_jsonld CLI command

### PR DESCRIPTION
**Pull request by azaroth42**
### Types of changes

-   [x] New feature (non-breaking change which adds functionality)

### Description of Change

Enable command line loading of JSON-LD data in the same way as JSON and CSV.

### Issues Solved

#6257

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by apeters** [comment]
@azaroth42 do you have some data I can test this against?

**Comment by azaroth42** [comment]
Here you go...

[test_load_cmd.zip](https://github.com/archesproject/arches/files/4897336/test_load_cmd.zip)

This is just some artificial data from the 6235 test.

To reproduce:
* Make a new project
* Uncompress the zip in the project root
* load the cidoc-crm ontology (pkg/ontology/cidoc_crm)
* load the model (pkg/models/)
* Then you can load the data:

> python ./manage.py load_jsonld -s pkg/data     

And you can experiment with the various options:

> python ./manage.py load_jsonld -s pkg/data --fast  6

This takes about 0.25 seconds, compared to 1.2 when saving each record individually, by batch save and index

> python ./manage.py load_jsonld -s pkg/data -m test   

This explicitly only loads the data in pkg/data/test ... if there were other directories, they'd be skipped

> python ./manage.py load_jsonld -s pkg/data --quiet

Doesn't announce every record

> python ./manage.py load_jsonld -s pkg/data --skip 1

Skips the first record  (e.g. if it's already loaded)

> python ./manage.py load_jsonld -s pkg/data  --max 1

Loads only the first record (e.g. for testing)

> python ./manage.py load_jsonld -s pkg/data --fast 6 --strip-issearchable

This uses my rewrite of get_documents_to_index to check node['issearchable'] and if it's false, don't even index it.
(This could be an option in core? Happy to do that refactor?)

**Comment by azaroth42** [comment]
I accept the second point. I'll make the suffix a required default, and filter out anything starting with `.`

The first is a reporting question. I chose to have it report the total number of records that it saw, not the total that it tried to load. If you look in the system, it will have skipped the right number of records -- if you do `--skip 3` it'll say that it saw 6, and it will have loaded 3. So it does the right thing, just has (obviously) unintuitive feedback to the user.

The same would be true if you put in ignore-errors ... it'll report all of them, even if only one got loaded and the rest were garbage. The rationale for this is about timing. I have always wanted to know how long it spent divided by all the records it saw ... if it loaded 50% and the rest caused some ignored error, then the timing statistics would be double the actual amount of time spent for the number of records.

A solution could be to have two counts -- total seen and total loaded?

**Comment by azaroth42** [comment]
Fixed the issues:
* every time it gets values from listdir() it filters out items that start with . or _
* Split the reporting into records seen and records loaded.
* Bonus: renamed force to ow/overwrite to be consistent with other commands

**Comment by apeters** [comment]
if you try to run any command more than once it throws an error

```
File"/Users/alexei/Work/Projects/arches4/arches/management/commands/load_jsonld.py", line 241, in load_resources
    loaded += l
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

**Pull request merged**
