### PR TITLE
fix logic within identity list creation

### PR DESCRIPTION
**Pull request by mradamcox**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
A small change to fix a logical issue that causes #10702 in specific cases. The diff should illustrate the issue clearly (it is localized to a single for loop)

### Issues Solved

#10702 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: FPAN - HMS
*   Found by: @mradamcox 
*   Tested by: @ 
*   Designed by: @ 

### Further comments

I am unable to attempt a test suite run on the master branch at this time.

### CODE REVIEW

**Comment by mradamcox** [comment]
Looks like CI is failing on webpack install.

**Comment by jacobtylerwalls** [comment]
Hi @mradamcox the failing build is because this PR targeted master. Although it's the default branch in the repo, we don't target PRs to it. Because this fixes an issue that raises an exception, I retargeted it to dev/7.5. That brought in some extra commits from 7.6. Could you rebase those out? Thanks!

**Comment by jacobtylerwalls** [comment]
Oh, one more thing. At the developer meeting last week it was encouraged to make the changelog update as part of a PR. A bullet in the 7.5.2.md document would do. Thanks.

**Comment by mradamcox** [comment]
Ok all set now, thanks @jacobtylerwalls.

**Review by jacobtylerwalls — APPROVED** [review]
Thanks!

**Pull request merged**
