### PR TITLE
Upgrade django to v3.2, re #8140

### PR DESCRIPTION
**Pull request by chiatt**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Upgrades django to v3.2, re #8140

### Issues Solved

#8140

### CODE REVIEW

**Comment by chiatt** [comment]
@apeters I tested both standard load and a bulk load and got the same results with both, so I don't think the model changes had any adverse impact. I also figured out why `edge.domainnode` and `edge.rangenode` were gettin improperly assigned in models/graph.copy. I added some inline comments in that method to help explain what's happening.

**Comment by chiatt** [comment]
@apeters To QA, all templates in your project must use {% load static %} instead of {% load staticfiles %}. I've made that change in this branch of HER:
https://github.com/archesproject/arches-her/pull/877

**Review by apeters — CHANGES_REQUESTED** [review]
I ran `makemigrations` and it generated this file
```
# Generated by Django 3.2.12 on 2022-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8140_django_upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsongeometry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmapsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='iiifmanifest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapmarker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mapsource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
```

We should probably update models.py to reflect those changes.  Other than that it looks good.

**Comment by chiatt** [comment]
@apeters That's a good catch. It turns out those models don't explicitly define primary keys, but I added those changes to the migration file (migrations/8140_django_upgrade.py).

**Review by njkim — APPROVED** [review]
Looks great to me!

**Pull request merged**
