### PR TITLE
working load of Kibana objects during package load, re #6735

### LINKED ISSUE #6735: Add process to load and manage Kibana spaces and objects from within the package loading process
Including integrating within the package load process add management commands to manage Kibana spaces and objects

### PR DESCRIPTION
**Pull request by apeters**
fixes #6735 

To test this you should first update your Elasticsearch to version 7.9, then you should install Kibana version 7.9
Then, you'll need to edit the config/kibana.yml by adding these configs:
server.basePath: "/kibana"
server.rewriteBasePath: true
Then start Kibana

Then install the USDSSC package.  After the package loads you should be able to see the kibana dashboard in the site.

### CODE REVIEW

**Review by chiatt — COMMENTED** [review]
@apeters It seems like the changes to settings.py should also be reflected in the settings.py-tpl file.

**Comment by apeters** [comment]
Thanks @chiatt I was going to do that, but just forgot!  Thanks for catching that!

**Review by chiatt — APPROVED** [review]
Works as expected

**Review by whatisgalen — APPROVED** [review]
works as expected

**Pull request merged**
