### PR TITLE
Demote no-ontologies UI error to a logged warning #9649

### LINKED ISSUE #9649: False error message when importing graph
When importing a graph without an ontology, the following error message appears. One would think that the graph failed to load, but despite the error it loads anyway.

image

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
There's nothing wrong with importing graphs into an environment without ontologies in their db. Demote this UI error to a logged warning.

### Issues Solved

Closes #9649

### CODE REVIEW

**Comment by chiatt** [comment]
I'm not sure if we should reduce this to a warning or actually prevent the graph from loading. If the graph loads, it will break until the ontologies are loaded.

**Comment by jacobtylerwalls** [comment]
But only for graphs with ontologies, right? I think that's what's checked in the `if` branch directly above. What if you never use ontologies in arches?

**Comment by chiatt** [comment]
> But only for graphs with ontologies, right? I think that's what's checked in the `if` branch directly above. What if you never use ontologies in arches?

Ah - indeed. I just needed to expand the code above your change to see that 'if'.

**Review by chiatt — APPROVED** [review]
Looks good!

**Pull request merged**
