### PR TITLE
The value in the date picker widget, #10125

### PR DESCRIPTION
**Pull request by njkim**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Fix the issue with the dirty state if the user cancels the date picked and picks the same day again, #10125

### Issues Solved

#10125

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
Fixes the underlying issue for me 👍 

But I'm noticing a slightly different behavior on this branch with cancelling edits if there's a default. I'm wondering if there's a way to keep the existing behavior?

***pr***
1. Configure the node to default to today's date
2. Open the resource editor, visit the widget, notice today's date defaulted
3. Pick tomorrow
4. Click cancel
Result: tomorrow's date still appears in the picker, but the string "Date of Data Entry" is sent to the server.


https://github.com/archesproject/arches/assets/38668450/5495971c-f8c0-4867-a20d-c065e231631c

***dev 7.5.x***
Result: "Date of Date Entry" appears in picker. Not great, but at least more clear to the user what the issue is.

date-of-data-entry

**Comment by chiatt** [comment]
@njkim Could you take a look at that `Date of Date Entry` issue as part of this PR as well?

**Review by jacobtylerwalls — COMMENTED** [review]
Hey @njkim I'm still noticing the original issue in #10125, but let me know if you prefer to have separate PRs for these fixes.


https://github.com/archesproject/arches/assets/38668450/27899efe-f107-4085-9557-89b787eb7342

**Comment by njkim** [comment]
Right, I was too focused on the widget with the default... :) I added the original logic back. It should be working now.
> Hey @njkim I'm still noticing the original issue in #10125, but let me know if you prefer to have separate PRs for these fixes.

**Comment by jacobtylerwalls** [comment]
Hold on, those might be existing issues on 7.5...

**Pull request merged**
