### PR TITLE
6673 allow app specific email config

### PR DESCRIPTION
**Pull request by csmith-he**
Referring to issue #6673 

Brief summary:

- New setting DEFAULT_FROM_EMAIL added to settings.py and settings.py-tpl
- Used for setting e-mail address in models\models.py
- In user.py:
  - Typo Fix in Email Subject Line
  - Replaced hardcoded App Name (i.e. Arches) with settings.APP_NAME to make configurable.

### CODE REVIEW

**Comment by csmith-he** [comment]
@chiatt, I've applied black (line length 140) to this PR (specifically user.py) and sticker-ci is still failing.  Please can you advise on next steps?  HE colleagues and I need to know what's going wrong before we submit any more PRs.  Cheers!

**Comment by chiatt** [comment]
Thanks @csmith-he, I'm looking into this.

**Review by chiatt — CHANGES_REQUESTED** [review]
This looks very good, but could you change the DEFAULT_FROM_EMAIL setting in both settings.py and settings.py-tpl to use the EMAIL_HOST_USER address by default?:
```
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Change if you need an alternate 'from' address for notifications that is different from your EMAIL_HOST_USER email address. 
```

**Comment by csmith-he** [comment]
@chiatt - I've made the requested change.  I also ran the file through black (line length 140) but despite the response coming back that the file had been reformatted, stickler-ci is staying it doesn't meet the style guide.

image

Basically I did exactly the same thing as I did for the other PR I sent in yesterday which worked so I'm a bit confused.

The CI step also seems to have failed:

image

Sorry to be causing more work with trying to get this change in - I'm just not quite sure what is going on here.

**Comment by chiatt** [comment]
Thanks @csmith-he, the build failure is actually my fault. I didn't think about the fact that `EMAIL_HOST_USER` would be commented out by default. Could you uncomment it in settings.py and settings.py-tpl so that it looks like this:

```
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'xxxx@xxx.com'
# EMAIL_HOST_PASSWORD = 'xxxxxxx'
# EMAIL_PORT = 587
```
If you push that change, the travis build should be fine. 

Once you make that change, I'll go ahead and merge it in. I think the formatting looks good, so we can disregard stickler in this case.

**Comment by csmith-he** [comment]
@chiatt - All done and it's passed travis this time so I think we're good to go if you're happy.

**Review by chiatt — APPROVED** [review]

**Pull request merged**
