### PR TITLE
Allow search control container to shrink if needed on smaller devices

### LINKED ISSUE #10994: On the search screen there are no page numbers to navigate to next set of results.
**Steps to reproduce:**

- Navigate to AHER search screen.
- On this screen the search results should display page numbers to navigate to next set of results.

**Expected:** Page numbers should display so that user can navigate to next set of search results.
**Actual:** When the screen is at 100% zoom the page numbers do not display whereas when zoomed out to 90% they appear.

**Note:** When Window height is smaller the issue arises.

image
image

### PR DESCRIPTION
**Pull request by phudson-he**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
When viewing the search results on devices with a smaller screen height, the pagination links were not visible and cant be scrolled to. This was due to a css flex value which wouldn't allow the container to shrink. This fix allows the container to shrink if needed. The other cross browser flex values were also changed accordingly to match.

Was looking like this...
image

...and now looks like this...

image

### Issues Solved

Closes #10994 

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [x] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @phudson-he 
*   Tested by: @phudson-he 
*   Designed by: @phudson-he

### CODE REVIEW

**Comment by whatisgalen** [comment]
it would be great to merge this into dev/7.6.x as well

**Comment by chiatt** [comment]
> Thanks for this change @phudson-he ! It would be great to merge this into dev/7.6.x as well

All bug fixes get merged periodically up to the next feature branch with a merge from 7.5.x -> 7.6.x -> 8.0.x

**Comment by whatisgalen** [comment]
> @whatisgalen @chiatt So I guess if approved and merged, we could just wait for the fix to make its way to 7.6/8.0?

I think I spoke too soon... the changes in my PR #10807 have style implications (read: regressions) for inline search components that need to be addressed, which is to say this fix is perfect for 7.5.x but won't have the same outcome for 7.6.x

**Comment by phudson-he** [comment]
@whatisgalen @chiatt Are we able to get this approved/merged into 7.5, but omit from 7.6?

**Pull request merged**
