### PR TITLE
4983 - First cut of custom map popup overlays

### PR DESCRIPTION
**Pull request by bferguso**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Provide ability to show custom text in the Map Popup overlays. Provides the ability to:
1. implement custom isFeatureClickable() function
2. provide custom popup template
3. format arbitrary map features into the required `displayname` and `map_popup` attributes shown on in the overlay

### Issues Solved

#4983 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @robgaston 
*   Tested by: @ 
*   Designed by: @bferguso 

### Further comments
Originally planned to implement this change by letting the templates do the heavy lifting, however once integrating #5307, multi-feature-popup, ended up following the primarydescriptors pattern and made the implementation more data-centric, allowing the source feature properties to be translated into `displayname` and `map_popup` observables consumed by the default template.

### CODE REVIEW

**Comment by bferguso** [comment]
I'm wondering if the default popup UI should be extended as part of this to be able to display > 4 lines for the map_popup primarydescriptor text. With the ability to customize the popup text for arbitrary features, it is likely that the map_popup can be longer than what is currently allowed for.

**Review by chiatt — CHANGES_REQUESTED** [review]
@bferguso I discussed this with @robgaston and we both agree this is a really nice change. However, we are trying to limit the introduction of new settings when reasonably possible. @robgaston noticed that you could remove the MAP_POPUP_CONFIG_PROVIDER setting by overriding map-popup-provider.js and/or map-popup.htm in your project. As long as the relative path in core matches the path in arches, the project file will be used instead of the core file. I think this would simplify things quite a bit and still be pretty easy for users to implement.

**Comment by chiatt** [comment]
I can see how it might be nice to show more than four lines in the default popup, but a height limit might still be useful to allow a vertical scrollbar to appear if a description happened to be really long. What do you think @dwuthrich

**Comment by bferguso** [comment]
@chiatt - Not introducing more config makes sense. I had originally done that so the overriding javascript could reference the base map-popup-provider.js but the default implementation is very simple so I totally agree. I'll remove all the config parts and resubmit.

**Review by chiatt — APPROVED** [review]

**Comment by chiatt** [comment]
Thanks very much @bferguso, this looks great. I spoke with @dwuthrich and @robgaston regarding the description height and the consensus was just to leave the default as is and let project implementer's customize it if they need to.

**Comment by bferguso** [comment]
@chiatt - That makes sense, thanks for letting me know.

**Pull request merged**
