### PR TITLE
added arches json support to resources put api

### PR DESCRIPTION
**Pull request by aj-he**
## Description

**Enhancement related to #6638** 

Resources API put method now supports arches json format as well as arches json-ld format.

## Checks
- [x] Run unit tests
- [x] Documentation already suggests json format is supported.
- [x] Tested on internal application at v5.0

### CODE REVIEW

**Comment by AJ-HistoricEngland** [comment]
@chiatt as promised

**Review by azaroth42 — CHANGES_REQUESTED** [review]
The API is now asymmetric. This updates only one of the possible operations via the resources/ endpoint, but not all of them. Would be good to make it consistent across all operations.

**Comment by AJ-HistoricEngland** [comment]
> The API is now asymmetric. This updates only one of the possible operations via the resources/ endpoint, but not all of them. Would be good to make it consistent across all operations.

@azaroth42 agreed. I only had time to implement the fix to PUT because our projecr only required this. GET already outputs Arches JSON. I believe only POST remains. Knowing how it implemented the PUT change, I don't think it will take too much work to get this into POST

**Comment by aj-he** [comment]
Just to update this ticket - we are still looking at adding this. We will be reviewing this to target 5.2.x in the next sprint planning.

**Comment by aj-he** [comment]
Closing as being superseded by #7470

**Pull request closed without merging**
