### PR TITLE
Create resource x record during ETL, #8431

### PR DESCRIPTION
**Pull request by njkim**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Create resource_x_resource record for resource instance datatype during ETL using db functions, re #8431

### Issues Solved

#8431

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by chiatt — COMMENTED** [review]
I'm wondering if this shouldn't be moved into its own function to reduce the length of this function and possibly make this new logic available to the relational schema. We should check in with @robgaston on this.

**Comment by robgaston** [comment]
worth noting we've got a database function to refresh these records on a per tile basis called `__arches_refresh_tile_resource_relationships`:
https://github.com/archesproject/arches/blob/ef95ef3b08204b33d2ee6aff457f38c2d295a89b/arches/app/models/migrations/7787_relational_data_model.py#L654-L699

**Comment by chiatt** [comment]
Good to know - thanks @robgaston

**Review by chiatt — APPROVED** [review]
Looks good to me!

**Pull request merged**
