### PR TITLE
Allows summary reports to leverage label based graph

### PR DESCRIPTION
**Pull request by chrabyrd**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

THIS NEEDS TO BE THOROUGHLY TESTED! -- it's a large architectural change and there's a chance some corner of our codebase has been missed. Please try to break this.

This feature should likely be squashed on merge, or let me know if you think it better I squash before merge. 160+ commits is _not_ fun to cherrypick :-)

Also this review may go quicker with some guidance to at least get the reviewer acquainted with the larger changes, happy to accommodate this any time.

The stickler failures are no-ops I believe

### Issues Solved

#7388

### CODE REVIEW

**Review by aarongundel — APPROVED** [review]

**Comment by apeters** [comment]
@chrabyrd can you fix these merge conflicts?  I don't feel like I know the changes well enough to make the determination.

**Comment by chrabyrd** [comment]
> @chrabyrd can you fix these merge conflicts? I don't feel like I know the changes well enough to make the determination.

done @apeters

**Review by apeters — CHANGES_REQUESTED** [review]
An error is thrown with the grouping card on line 39.  
```grouping.js?_dc=5.2.0b0:39 Uncaught TypeError: Cannot read property 'cards' of undefined```

**Comment by chrabyrd** [comment]
> An error is thrown with the grouping card on line 39.
> `grouping.js?_dc=5.2.0b0:39 Uncaught TypeError: Cannot read property 'cards' of undefined`
> 
> See the second tab of an AFS "Project" instance for an example

Done and done :)

**Comment by apeters** [comment]
I found this error when using the Image Header Report template. This seems to be intermittent, when I refresh the page twice in succession.

resource-report-abstract.js?_dc=5.2.0b0:105 Uncaught (in promise) TypeError: CardViewModel is not a constructor

**Review by apeters — APPROVED** [review]
There is still one outstanding minor issue which I'll make a ticket for, but otherwise this works as expected.

**Pull request merged**
