### PR TITLE
11099 download ready email

### PR DESCRIPTION
**Pull request by csmith-he**
### Types of changes

-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Move the {% if link =! "" %} section outside of the {% if files %} section so that this part of the template works whether or not files are within the context

### Issues Solved
#11099 
Also related to https://github.com/archesproject/arches-her/issues/1233

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [X] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: Goutham Randhi (tester, Historic England)
*   Tested by: @csmith-he

### Further comments

Without this fix, there may be issues with sending download ready emails in instances where no files are generated

### CODE REVIEW

**Comment by chiatt** [comment]
Shouldn't we just notify the user that there is nothing to download rather than provide a link?

**Comment by csmith-he** [comment]
> Shouldn't we just notify the user that there is nothing to download rather than provide a link?

@chiatt 

This is possibly me not being clear - in our use case (i.e. emails for Arches for HERs), there doesn't appear to be a files object but there is a link to download the CSV export

**Comment by chiatt** [comment]
> > Shouldn't we just notify the user that there is nothing to download rather than provide a link?
> 
> @chiatt
> 
> This is possibly me not being clear - in our use case (i.e. emails for Arches for HERs), there doesn't appear to be a files object but there is a link to download the CSV export (i.e. there is a file generated for the download)

Ah, I see. That makes sense. Thanks @csmith-he

**Review by chiatt — APPROVED** [review]
Looks good to me!

**Pull request merged**
