### PR TITLE
Adds database spatial views

### PR DESCRIPTION
**Pull request by aj-he**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Adds new SpatialView model that manages spatial views in the database via triggers and functions.

Creates arches_spatial_views role for connecting via pg_featureserv e.g. `postgresql://arches_spatial_views:arches_spatial_views@localhost:5432/dbname`

Doesn't support custom PrimaryDisplayDescriptor classes.

example insert to spatial_views table (based on arches-her models):
```sql
INSERT INTO public.spatial_views(
	spatialviewid, schema, slug, description, ismixedgeometrytypes, attributenodes, isactive, geometrynodeid)
	VALUES (
		'a866f4f8-aeac-11ec-b909-0242ac120002'::uuid
		, 'public'
		, 'heriage_asset'
		, 'Heritage Asset view description'
		, false
		, '[
			{"nodeid":"325a2f33-efe4-11eb-b0bb-a87eeabdefba","description":"test field description"},
			{"nodeid":"676d47ff-9c1c-11ea-b07f-f875a44e0e11","description":"The names of the Heritage Asset. See the order of Name asset type to determine which type they are."}
		  ]'::jsonb
		, true
		, '87d3d7dc-f44f-11eb-bee9-a87eeabdefba'::uuid);
``` 
example that generates all views for arches-her
```sql
WITH aher_sp_views AS (
	SELECT
		uuid_generate_v4() AS spatialviewid,
		'public' as schema,
		__arches_slugify(g.name) as slug,
		g.description,
		false AS ismixedgeometrytypes,
		json_agg(
				json_build_object(
					'nodeid', n.nodeid, 
					'description', __arches_slugify(n.name)
				)
			) as attributenodes,
		true as isactive,
		geo_n.nodeid as geometrynodeid
	FROM (SELECT * FROM nodes WHERE nodeid::text in
		  -- attribute nodeids across models 
		('87d3d7dc-f44f-11eb-bee9-a87eeabdefba','325a2f33-efe4-11eb-b0bb-a87eeabdefba','676d47ff-9c1c-11ea-b07f-f875a44e0e11','77e8f28d-efdc-11eb-afe4-a87eeabdefba','77e8f29d-efdc-11eb-b890-a87eeabdefba','b2133e6b-efdc-11eb-aa04-a87eeabdefba','b2133e72-efdc-11eb-a68d-a87eeabdefba','ba345577-b554-11ea-a9ee-f875a44e0e11','6af2a0ce-efc5-11eb-88d1-a87eeabdefba,a5419248-f121-11eb-86a9-a87eeabdefba','2a5b99ad-fe48-11ea-84a1-f875a44e0e11','394d15b8-8f7a-11ea-b4f5-f875a44e0e11','4a7be135-9938-11ea-b0e2-f875a44e0e11','4f5eeb27-993e-11ea-b9f7-f875a44e0e11','be3831a5-813e-11e9-9a94-80000b44d1d9','e7d69602-9939-11ea-b514-f875a44e0e11,1909956f-3a3b-11eb-ae99-f875a44e0e11','48509bd3-83d4-11ea-9923-f875a44e0e11','9c9f9dc0-83bf-11ea-8d22-f875a44e0e11','d6734e3d-94fb-11ea-b836-f875a44e0e11,b949053a-184f-11eb-ac4a-f875a44e0e11','1b0e15ec-8864-11ea-8493-f875a44e0e11','40eff4cd-893a-11ea-b0cc-f875a44e0e11','4ad69684-951f-11ea-b5c3-f875a44e0e11','54de6acc-8895-11ea-9067-f875a44e0e11','73fdfe62-8895-11ea-a058-f875a44e0e11','b37552bd-9527-11ea-97f4-f875a44e0e11','c128bf36-9384-11ea-bfe1-f875a44e0e11,64be56e3-3ee5-11eb-b1f0-f875a44e0e11','d17aa1e4-28cd-11eb-83b8-f875a44e0e11','8dca12b3-edeb-11eb-a9ee-a87eeabdefba','a4a816e6-efa9-11eb-b0de-a87eeabdefba','a4a816f0-efa9-11eb-969d-a87eeabdefba','b334dde5-4e87-11eb-9576-f875a44e0e11','b334dde6-4e87-11eb-a67c-f875a44e0e11','ed6c28c2-1861-11eb-9f92-f875a44e0e11','ed6c28c3-1861-11eb-9f6e-f875a44e0e11','f3cc1684-185b-11eb-9a07-f875a44e0e11','f45dbbe8-80b7-11ea-b325-f875a44e0e11,9766b0d4-f450-11eb-83b6-a87eeabdefba','20d7355e-28e1-11eb-bdbc-f875a44e0e11','446d5c4c-3e14-11eb-8095-f875a44e0e11','490c26da-efe9-11eb-abc4-a87eeabdefba','7f5591c5-efed-11eb-8e44-a87eeabdefba','daa1dd37-5a08-11e9-b6c9-18cf5eb368c4,9f07fa25-f457-11eb-98c7-a87eeabdefba','656c41b0-3ec0-11eb-8d87-f875a44e0e11','656c68c4-3ec0-11eb-859a-f875a44e0e11','72996ee3-3ecb-11eb-ad29-f875a44e0e11','72996eeb-3ecb-11eb-9e47-f875a44e0e11','d00d4c8c-299f-11eb-bc0e-f875a44e0e11','ed3c32e6-29a1-11eb-82fa-f875a44e0e11','f1cbd897-f007-11eb-8b4b-a87eeabdefba,6678040f-3dff-11eb-a042-f875a44e0e11','3d22bf22-1aa8-11eb-a368-f875a44e0e11','4a1e7dc7-f000-11eb-ac44-a87eeabdefba','4cf307e2-07b5-11eb-8253-f875a44e0e11','89a3e510-07b9-11eb-b1b2-f875a44e0e11','e354c5b3-07b8-11eb-8416-f875a44e0e11,38521798-3bd0-11eb-ad57-f875a44e0e11','4365828a-99e3-11ea-b6fb-f875a44e0e11','44441e0c-99ac-11ea-97cc-f875a44e0e11','4bc44105-99aa-11ea-aaa3-f875a44e0e11','b2d194c6-99aa-11ea-b5eb-f875a44e0e11,f7ccc8b9-f447-11eb-9cb1-a87eeabdefba','5b0dfb27-7fe2-11ea-8ac9-f875a44e0e11','dd8032af-b494-11ea-8110-f875a44e0e11','dd8032b1-b494-11ea-a183-f875a44e0e11','c30977b0-991e-11ea-ba04-f875a44e0e11','546b1630-3ba4-11eb-9030-f875a44e0e11','99cfffd1-381d-11e8-ab51-dca90488358a','99cfe72e-381d-11e8-882c-dca90488358a','99cff7f8-381d-11e8-a059-dca90488358a','22e7c550-afc2-11ea-a4a8-f875a44e0e11','50edbf22-ab25-11ea-a258-f875a44e0e11')
		AND (datatype NOT LIKE '%geojson%' AND datatype NOT LIKE '%semantic%') n
		Join graphs g on n.graphid = g.graphid
		JOIN (select * from nodes where nodeid::text in 
			  		-- geojson nodeids across models
				(
					'87d3d7dc-f44f-11eb-bee9-a87eeabdefba',
					'a5419248-f121-11eb-86a9-a87eeabdefba',
					'1909956f-3a3b-11eb-ae99-f875a44e0e11',
					'b949053a-184f-11eb-ac4a-f875a44e0e11',
					'64be56e3-3ee5-11eb-b1f0-f875a44e0e11',
					'9766b0d4-f450-11eb-83b6-a87eeabdefba',
					'9f07fa25-f457-11eb-98c7-a87eeabdefba',
					'6678040f-3dff-11eb-a042-f875a44e0e11',
					'38521798-3bd0-11eb-ad57-f875a44e0e11',
					'f7ccc8b9-f447-11eb-9cb1-a87eeabdefba'
				)) geo_n on g.graphid = geo_n.graphid
	Group by __arches_slugify(g.name),geo_n.nodeid,g.description
	order by __arches_slugify(g.name)
)
INSERT INTO spatial_views SELECT * FROM aher_sp_views;
```

### Issues Solved

#8042 

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @aj-he  
*   Tested by: @aj-he 
*   Designed by: @aj-he

### CODE REVIEW

**Comment by aj-he** [comment]
@robgaston here is the initial PR for the database spatial view functionality. I have not yet put it though its paces with a full arches-her data load yet, but it looks to be broadly working following the pattern we discussed. Have a look and see what you think.

Happy to merge the migrations later but for now it helps with them being in 3 distinct chunks.

**Review by robgaston — CHANGES_REQUESTED** [review]
@aj-he The looks good enough for merge at this point, as it is a new feature and risk is low. It seems to work well in my testing.

We can refactor the resource instance name look up stuff here once we have a fix for #8301, which should be incoming.

One thing: can you merge in the latest from https://github.com/archesproject/arches/tree/dev/6.1.x and then re-run the build job (which that merge should automatically trigger)?  (I did this merge locally and the tests ran fine for me afterwards)

Thanks!

**Comment by robgaston** [comment]
@aj-he it looks like the tests maybe failing because they are using PostgreSQL 10 which does not support `create or replace aggregate`

@chiatt can you confirm that the tests in GitHub use PostgreSQL 10?  How would you recommend going forward here?

**Comment by robgaston** [comment]
@aj-he I talked to @chiatt and we agreed that the best way forward was to upgrade the version of PostgreSQL/PostGIS to 13/3 in our GitHub build.  Could you please update the yaml file (https://github.com/archesproject/arches/blob/dev/6.1.x/.github/workflows/main.yml#L13) in your branch to address this (since this PR is from your fork I cannot make that change myself at the moment).  Thanks!

**Comment by aj-he** [comment]
> @aj-he I talked to @chiatt and we agreed that the best way forward was to upgrade the version of PostgreSQL/PostGIS to 13/3 in our GitHub build. Could you please update the yaml file (https://github.com/archesproject/arches/blob/dev/6.1.x/.github/workflows/main.yml#L13) in your branch to address this (since this PR is from your fork I cannot make that change myself at the moment). Thanks!

@robgaston I've updated this and it looks like the test is not failing on the db code anymore. so that's good.

I have locally merged in latest dev/6.1.x and also applied a fix we have done internally caused by having a unique index on the attributes tables.  I need to run an extra test to see if that is working ok before I push.

**Comment by aj-he** [comment]
@robgaston I've updated as requested and brought up to date. The unique index fix is in also. I can't get my black formatter to format the big string block in the 3rd migration file so I think the stickler check will continue to fail it.

**Review by robgaston — APPROVED** [review]
Looks & works good for me.  Thanks!

**Comment by reubenosborne1** [comment]
Hi @robgaston @aj-he. 

I'm trying to use this, maybe you can help point me where I'm going wrong? I have this really simple model and view:

image

and it throws back this error which I am struggling to debug:

```
  File "/home/rosborne/Projects/arches_dev/env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 240, in _commit
    return self.connection.commit()
django.db.utils.ProgrammingError: syntax error at or near "ec"
LINE 9: ..._node_display_value(distinct tile_c6b85084-ebc7-11ec-abc3-fd...
                                                             ^
QUERY:  
                        create table public.sp_attr_location_test_view 
                        tablespace pg_default
                        as
                        (
                            select 
                                r.resourceinstanceid::text as resourceinstanceid
                                
                                    ,__arches_agg_get_node_display_value(distinct tile_c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb.tiledata, 'c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb') as name
                                    
                            from resource_instances r
                                join geojson_geometries geo on geo.resourceinstanceid::text = r.resourceinstanceid::text
                                    and geo.nodeid = 'ce5002ce-ebc7-11ec-abc3-fd81cfe5ffeb'
                                 
                                    left outer join tiles tile_c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb on r.resourceinstanceid = tile_c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb.resourceinstanceid
                                        and tile_c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb.nodegroupid = 'c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb'
                                    
                            group by
                                r.resourceinstanceid::text
                        )
                        with data;
                        
                        comment on column public.sp_attr_location_test_view.resourceinstanceid is 'Globally unique Arches resource ID';comment on column public.sp_attr_location_test_view.name is 'name field';

                        create index on public.sp_attr_location_test_view (resourceinstanceid);
                        
                        
CONTEXT:  PL/pgSQL function __arches_create_spatial_view_attribute_table(text,uuid,jsonb,text) line 100 at EXECUTE
PL/pgSQL function __arches_create_spatial_view(text,uuid,jsonb,text,text,boolean) line 12 at assignment
PL/pgSQL function __arches_update_spatial_view(text,text,text,uuid,jsonb,text,text,boolean) line 8 at assignment
SQL statement "select __arches_update_spatial_view('location_test_view', 'public', 'location_test_view', 'ce5002ce-ebc7-11ec-abc3-fd81cfe5ffeb'::uuid, '[{"nodeid": "c6b85084-ebc7-11ec-abc3-fd81cfe5ffeb", "description": "name field"}]'::jsonb, 'public', 'arches spatial view', 'f');"
PL/pgSQL function __arches_trg_fnc_update_spatial_views() line 90 at EXECUTE
```

**Pull request merged**
