### PR TITLE
enforces ordering in bulk disambiguated endpoint #9988

### PR DESCRIPTION
**Pull request by chrabyrd**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Issues Solved

#9988

### CODE REVIEW

**Comment by njkim** [comment]
The original order isn't retained for me.

It looks like the json is reordered by this line, even though the ordered dictionary is passed,
https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/betterJSONSerializer.py#L79
through
https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/response.py#L18

So if resorting by the key isn't desirable, it seems sort_keys needs to be set to False.

**Review by njkim — CHANGES_REQUESTED** [review]
The original order isn't retained for me.

It looks like the json is reordered by this line, even though the ordered dictionary is passed,
https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/betterJSONSerializer.py#L79
through
https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/response.py#L18

So if resorting by the key isn't desirable, it seems sort_keys needs to be set to False.

**Comment by chrabyrd** [comment]
> The original order isn't retained for me.
> 
> It looks like the json is reordered by this line, even though the ordered dictionary is passed, https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/betterJSONSerializer.py#L79 through https://github.com/archesproject/arches/blob/dev/7.5.x/arches/app/utils/response.py#L18
> 
> So it seems sort_keys=False needs to be passed, if resorting by the key isn't desirable.

good catch!

**Review by njkim — APPROVED** [review]
It looks good and works as expected.

**Pull request merged**
