### PR TITLE
Add language support into DB functions and model tests and validation

### LINKED ISSUE #10705: Update Spatial Views to factor in internationisation
Spatial Views do not currently handle internationalisation (i.e. language element) which will cause problems when populating attributes with string values from the data held in an Arches instance.

Spatial Views need to be updated to handle internationalisation.

### PR DESCRIPTION
**Pull request by aj-he**
### Types of changes

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Updates to spatialview database functions for language support and improved testing/validation

- Updates all spatial view database functions to use the spatialview language code to fetch correct value.
- Adds SpatialView model validation on save()
- Adds some QoL to spatial views when using Django Admin (geometrynode validator)
- Adds SpatialView model tests
- Fixes test using TransactionTestCase to stop premature truncation of the test database.

### Issues Solved

Closes #10705

### Checklist

-   I targeted one of these branches:
    - [x] dev/7.6.x (under development): features, bugfixes not covered below
    - [ ] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [x] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [x] Unit tests pass locally with my changes
-   [x] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Accessibility Checklist

[Developer Guide](https://arches.readthedocs.io/en/stable/developing/advanced/accessibility/)

| Topic            | Changed | Retested |
| ---------------- | ------- | -------- |
| Color contrast   |         |          |
| Form fields      |         |          |
| Headings         |         |          |
| Links            |         |          |
| Keyboard         |         |          |
| Responsive Design|         |          |
| HTML validation  |         |          |
| Screen reader    |         |          |

#### Ticket Background
*   Sponsored by: Historic England
*   Designed by: @aj-he
*   Supported by: @whatisgalen 

### Further comments

This change is in combination with #10704, which added language code to the Spatialview model and is providing an API to manage them outside django admin.

### CODE REVIEW

**Comment by aj-he** [comment]
@whatisgalen I have no idea why all these checks are failing as the migrations all work as expected on my local machine?

**Comment by jacobtylerwalls** [comment]
Hey Andy. The check is saying there's a "missing" migration, so you just need to run makemigrations.

**Comment by jacobtylerwalls** [comment]
Hey all. I followed up on Slack, but basically we can just add `serialized_rollback = True` and everything should work without having to manually manage the truncation (modulo a couple changes to the user signals). You can borrow what you need from d7c1f60f2f7ec31a355b7ddce29ca5c5ba9eba50, I hope?

**Comment by aj-he** [comment]
@jacobtylerwalls I've implemented the `serialized_rollback = True` approach and remove all the class methods, which works in isolation.  However, the `tests/bulkdata/single_csv_tests.py` test is causing an issue, even with the changes you made in the commit you reference (move code out of the class methods and modify).

The error refers to missing ContentType, which makes me think that truncation is occurring prematurely...
`django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.`

If I remove the single_csv_tests TransactionTestCase then it works fine.

**Comment by jacobtylerwalls** [comment]
Hey @aj-he. That's the failure I see when I don't include the changes to the save_profile() and create_permissions_for_new_users() signals in that commit. Just checking that you included those changes as well?

**Comment by aj-he** [comment]
@jacobtylerwalls - yep, that was it! I didn't pick up on those signal tweaks. This branch has gotten a bit dirty so I'm going to close this PR and rebase tidying up. It also depends on your commits mentioned so will need to wait for those to go through. Thanks

**Pull request closed without merging**
