### PR TITLE
Create a new geom in a separate card, Esri#141 

### PR DESCRIPTION
**Pull request by njkim**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change

Fix the error failing to create a geom node using node_value api by ArcGIS Pro addin
archesproject/arches-esri-add-in#141

### Issues Solved

archesproject/arches-esri-add-in#141

### Checklist

-   [ ] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: 
*   Found by: @ 
*   Tested by: @ 
*   Designed by: @

### CODE REVIEW

**Review by chiatt — COMMENTED** [review]
@njkim This looks okay to me, but I've asked @apeters to also have a look.

**Review by apeters — CHANGES_REQUESTED** [review]
I would recommend that we refactor this a bit more.

- First I would  leverage `get_blank_tile_from_nodegroup_id` in creating the parent tile (lines 547-551)
- Second, I would move the check for semantic nodes into `get_blank_tile_from_nodegroup_id` (this will also fix this issue re #6902)

**Review by chiatt — APPROVED** [review]
Looks good to me

**Review by apeters — APPROVED** [review]
This looks good to me.  We should also confirm that this fixes re #6902

**Pull request merged**
