### PR TITLE
Extend compatibility to Win64 OS on importer.py

### PR DESCRIPTION
**Pull request by azerbini**
Circumvent 32bit C long limit on Win64 by handling TypeError exception
thrown by csv.limit_file_size.

### Description of Change

Add exception to handle TypeError raised when sys.maxsize != sys.maxint as is the case in Win64 environments.

### Issues Solved

csv importer now working on Win64 environments.

### Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist

- [x] Unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by jmunowitch** [comment]
Hi @azerbini: I am unsure of how to test that this would work. Do you have data files that would make this reproducible?

**Comment by mradamcox** [comment]
This is why I approve this PR: 
image

**Comment by mradamcox** [comment]
looking at the conflict, I think this is just way too old at this point. the importer.py file has changed so significantly that I'm not even sure where this fix should be implemented anymore. I'll leave this open for now, but even though the actual code is fine, I would vote to close the PR without merging.

**Comment by jmunowitch** [comment]
I am going to close this for now, based upon @mradamcox's suggestion.

We can always re-open the PR once this is updated to a more recent branch.

**Comment by mradamcox** [comment]
@azerbini @jmunowitch just wanted to see what it would look like to merge this into stable/3.x... not good :) closing again.

**Pull request closed without merging**
