### PR TITLE
8770 - Add reference to new and old values in bulk_index_queue insert…

### PR DESCRIPTION
**Pull request by bferguso**
… statements

### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
Add missing old/new value references to update triggers

### Issues Solved

#8770 

### Checklist

-   [x] Unit tests pass locally with my changes
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] I have added necessary documentation (if appropriate)

#### Ticket Background
*   Sponsored by: Self Funded
*   Found by: @bferguso
*   Tested by: @bferguso
*   Designed by: @bferguso

### CODE REVIEW

**Comment by chiatt** [comment]
@robgaston & @aarongundel - In case you haven't looked at this PR yet, @bferguso has made a new migration which modifies the trigger functions defined in the `8403_relational_data_model.py` migration. Because this is a migration in 6.2, we really should have it in v7 as well to maintain the same migration dependency order for people eventually migrating from 6.2 to 7.0. So, I've added v7 to the release target in his ticket and raised the priority.

To make review a bit easier, I've applied Brett's changes to 8403_relational_data_model.py in a temporary branch so that you can see the exact changes that were made: [8403_relational_data_model.py](https://github.com/archesproject/arches/compare/dev/6.2.x...diff_8771)

**Review by aarongundel — APPROVED** [review]
Validated the issue and the fix - worked for me and looks good!

**Comment by bferguso** [comment]
Thanks @aarongundel. 
@aarongundel, @chiatt - How would you like this merged into dev/7.0.x? Is there another merge coming through from dev/6.2.x or should it be cherry picked?

**Comment by robgaston** [comment]
@bferguso we will merge this into 7 with the rest of the latest from the 6 branch. please stand by -- thanks!

**Comment by bferguso** [comment]
Thanks @robgaston. No pressure from here as we're still working from 6.2.x. Just making sure you have everything you need from me.

**Pull request merged**
