### PR TITLE
Fix for report height scrolling issue

### LINKED ISSUE #11124: Report height/scrolling issues on devices with a smaller available height
An issue was found while working on an [AfHER ticket](https://github.com/archesproject/arches-her/issues/1246). Under certain circumstances if using a device with a smaller available height, the report, edit report, and report details doesn't allow the user to scroll to the bottom to see all of the content. For this to work in AfHER, there needs to be a change in core to the following file: /templates/views/components/resource-report-abstract.htm

A hotfix was merged into the 1077 aher branch which will be removed when this fix has been merged.

**Steps to reproduce:**

1. Open search page
2. Click on a "Details" link on one of the search results
3. Reduce the web browser height
4. Look at the right scrollbar - cant scroll to the bottom to see Citations section

image

### PR DESCRIPTION
**Pull request by phudson-he**
### Types of changes

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Description of Change
This will fix an issue where when viewing on a device with a smaller available height, and the user would not be able to scroll down far enough to view all of the content. As said in the issue, this was identified while working on a aher ticket, where a hotfix was applied and will be removed once this is in core etc.

### Issues Solved

Closes #11124 

### Checklist

-   I targeted one of these branches:
    - [ ] dev/7.6.x (under development): features, bugfixes not covered below
    - [x] dev/7.5.x (main support): regressions, crashing bugs, security issues, major bugs in new features
    - [ ] dev/6.2.x (extended support): major security issues, data loss issues
-   [ ] I added a changelog in arches/releases
-   [ ] I submitted a PR to arches-docs (if appropriate)
-   [ ] Unit tests pass locally with my changes
-   [ ] I added tests that prove my fix is effective or that my feature works
-   [ ] My test fails on the target branch

#### Ticket Background
*   Sponsored by: Historic England
*   Found by: @phudson-he 
*   Tested by: @phudson-he 
*   Designed by: @phudson-he

### CODE REVIEW

**Comment by aj-he** [comment]
@phudson-he - that `reportSummary` class is not in core Arches. You should double check you included everything you need

**Comment by phudson-he** [comment]
Yes indeed that should be included, thanks for spotting, working on it now

**Comment by phudson-he** [comment]
CSS implemented for class .reportSummary. Although this doesn't look like it would do anything as the .resource-component-abstract class already has overflow-y: auto, this is required when using aher. It does not affect anything else, just re-affirms the overflow-y value.

**Comment by aj-he** [comment]
This PR is being tracked here... https://github.com/archesproject/arches-her/issues/1246

**Comment by aj-he** [comment]
converted to draft to resolve erroneous commit.

**Comment by chiatt** [comment]
@phudson-he I haven't been able to reproduce #11124. Looking at this this [report](https://herdemo.archesproject.org/report/0a1583e0-7c96-47fb-bc87-e0a5e5dc5479), there doesn't seem to be a problem scrolling to all of the content of the report. Even simulating an iPhone in landscape, I can get to the bottom of the content.

image

Is there a particular model and report tab where you are seeing it?

**Comment by phudson-he** [comment]
Thanks @chiatt, I will take another look

**Comment by phudson-he** [comment]
@chiatt I'm still re-looking at this, but just to be clear it's more to do with scrolling to the bottom of the details (from Details link) report view, rather than the default report view.

**Comment by chiatt** [comment]
Thanks @phudson-he, I'll take a close look at the details.

**Comment by phudson-he** [comment]
Closing this as it's an arches-her issue and was fixed with this: https://github.com/archesproject/arches-her/pull/1284

**Pull request closed without merging**
